/**
 * gsocMeta.js — per-country provenance metadata for FAO GSOCmap v1.6.
 *
 * Source: FAO. 2022. Global Soil Organic Carbon Map — GSOCmap v.1.6.
 * Technical report. Rome. https://doi.org/10.4060/cb9015en (Annex D,
 * "GSOCmap submission overview", printed pp. 76-238).
 * Extracted: 2026-09-21. 195 country entries (report skips index numbers
 * D134 and D152; no country is missing).
 *
 * Keyed by ISO3 code; a country name is used as the key only where no
 * unambiguous ISO3 exists (none in this version). gap_filled is "yes"
 * when the layer was produced by the GSP Secretariat gap-filling or
 * taken from an external product (SoilGrids 2.0), "no" for country
 * submissions and joint efforts (see each entry's notes).
 *
 * Draft lookup module — plain data, no Earth Engine API calls.
 * Usage: var gsocMeta = require('users/andyarnellgee/apps:modules/gsocMeta.js');
 */

var META = {
  "AFG": {"country_name": "Afghanistan", "iso3": "AFG", "institution": "FAO Afghanistan", "methodology": "Digital soil mapping (Random forest)", "n_samples": "384", "sampling_period": "before and after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 76"},
  "ALB": {"country_name": "Albania", "iso3": "ALB", "institution": "ISRIC World Soil Information", "methodology": "External product (SoilGrids 2.0)", "n_samples": "", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: External (soilgrids.org). Layer taken from SoilGrids 2.0 (Poggio et al. 2021), not a national submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 77"},
  "DZA": {"country_name": "Algeria", "iso3": "DZA", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Support vector machines)", "n_samples": "16", "sampling_period": "before 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 77"},
  "AND": {"country_name": "Andorra", "iso3": "AND", "institution": "European Soil Data Centre (ESDAC)", "methodology": "Digital soil mapping (Support vector machines)", "n_samples": "0", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 78"},
  "AGO": {"country_name": "Angola", "iso3": "AGO", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Random forest)", "n_samples": "962", "sampling_period": "before and after 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 79"},
  "ATG": {"country_name": "Antigua and Barbuda", "iso3": "ATG", "institution": "ISRIC World Soil Information", "methodology": "External product (SoilGrids 2.0)", "n_samples": "", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: External (soilgrids.org). Layer taken from SoilGrids 2.0 (Poggio et al. 2021), not a national submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 80"},
  "ARG": {"country_name": "Argentina", "iso3": "ARG", "institution": "Instituto Nacional de Tecnologia Agropecuaria (INTA)", "methodology": "Digital soil mapping (Random forest + QRF)", "n_samples": "5073", "sampling_period": "before and after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 81"},
  "ARM": {"country_name": "Armenia", "iso3": "ARM", "institution": "Soil Science, Melioration and Agrochemistry Scientific Center named after H. Petrosyan", "methodology": "Digital soil mapping (Other)", "n_samples": "40", "sampling_period": "after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 82"},
  "AUS": {"country_name": "Australia", "iso3": "AUS", "institution": "CSIRO Agriculture and Food", "methodology": "Digital soil mapping (Mixed)", "n_samples": "5588", "sampling_period": "after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 82"},
  "AUT": {"country_name": "Austria", "iso3": "AUT", "institution": "Dpt. for forest ecology and soil", "methodology": "Conventional upscaling (Mixed)", "n_samples": "150511", "sampling_period": "before and after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 83"},
  "AZE": {"country_name": "Azerbaijan", "iso3": "AZE", "institution": "Institute of Soil Science and Agrochemistry of ANAS", "methodology": "Conventional upscaling (Geomatching / Class-matching)", "n_samples": "430", "sampling_period": "after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 84"},
  "BHS": {"country_name": "Bahamas", "iso3": "BHS", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Other)", "n_samples": "0", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 85"},
  "BHR": {"country_name": "Bahrain", "iso3": "BHR", "institution": "ISRIC World Soil Information", "methodology": "External product (SoilGrids 2.0)", "n_samples": "", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: External (soilgrids.org). Layer taken from SoilGrids 2.0 (Poggio et al. 2021), not a national submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 86"},
  "BGD": {"country_name": "Bangladesh", "iso3": "BGD", "institution": "ISRIC World Soil Information", "methodology": "External product (SoilGrids 2.0)", "n_samples": "", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: External (soilgrids.org). Layer taken from SoilGrids 2.0 (Poggio et al. 2021), not a national submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 86"},
  "BRB": {"country_name": "Barbados", "iso3": "BRB", "institution": "ISRIC World Soil Information", "methodology": "External product (SoilGrids 2.0)", "n_samples": "", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: External (soilgrids.org). Layer taken from SoilGrids 2.0 (Poggio et al. 2021), not a national submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 87"},
  "BLR": {"country_name": "Belarus", "iso3": "BLR", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Support vector machines)", "n_samples": "88", "sampling_period": "before and after 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 87"},
  "BEL": {"country_name": "Belgium", "iso3": "BEL", "institution": "Vlaamse overheid and Service Public de Wallonie, with university partners", "methodology": "Digital soil mapping (Mixed)", "n_samples": "2457", "sampling_period": "after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 88"},
  "BLZ": {"country_name": "Belize", "iso3": "BLZ", "institution": "ISRIC World Soil Information", "methodology": "Digital soil mapping (Random forest)", "n_samples": "20", "sampling_period": "external datasets", "gap_filled": "yes", "notes": "Map source: GSP gap-filling. Report gives 'external datasets' for some data-specification fields.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 90"},
  "BEN": {"country_name": "Benin", "iso3": "BEN", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Random forest)", "n_samples": "714", "sampling_period": "before and after 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 91"},
  "BTN": {"country_name": "Bhutan", "iso3": "BTN", "institution": "National Soil Services Centre, Department of Agriculture, Ministry of Agriculture and Forests", "methodology": "Digital soil mapping (Mixed)", "n_samples": "993", "sampling_period": "after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 92"},
  "BOL": {"country_name": "Bolivia (Plurinational State of)", "iso3": "BOL", "institution": "Viceministerio de Tierras", "methodology": "Digital soil mapping (Random forest)", "n_samples": "4788", "sampling_period": "before and after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 93"},
  "BIH": {"country_name": "Bosnia and Herzegovina", "iso3": "BIH", "institution": "University of Sarajevo", "methodology": "Digital soil mapping (Random forest)", "n_samples": "1715", "sampling_period": "before and after 1990", "gap_filled": "no", "notes": "Map source: Joint effort with GSP. Map produced jointly by the country and the GSP Secretariat.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 94"},
  "BWA": {"country_name": "Botswana", "iso3": "BWA", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Random forest)", "n_samples": "839", "sampling_period": "before 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 95"},
  "BRA": {"country_name": "Brazil", "iso3": "BRA", "institution": "Embrapa Solos", "methodology": "Digital soil mapping (Mixed)", "n_samples": "6998", "sampling_period": "before and after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 96"},
  "BRN": {"country_name": "Brunei Darussalam", "iso3": "BRN", "institution": "ISRIC World Soil Information", "methodology": "External product (SoilGrids 2.0)", "n_samples": "", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: External (soilgrids.org). Layer taken from SoilGrids 2.0 (Poggio et al. 2021), not a national submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 97"},
  "BGR": {"country_name": "Bulgaria", "iso3": "BGR", "institution": "European Soil Data Centre (ESDAC)", "methodology": "Digital soil mapping (Support vector machines)", "n_samples": "664", "sampling_period": "after 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 97"},
  "BFA": {"country_name": "Burkina Faso", "iso3": "BFA", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Random forest)", "n_samples": "532", "sampling_period": "before and after 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 98"},
  "BDI": {"country_name": "Burundi", "iso3": "BDI", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Random forest)", "n_samples": "34", "sampling_period": "before 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 99"},
  "KHM": {"country_name": "Cambodia", "iso3": "KHM", "institution": "DALRM, General Directorate of Agriculture", "methodology": "Digital soil mapping (Regression Kriging)", "n_samples": "671", "sampling_period": "after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 100"},
  "CMR": {"country_name": "Cameroon", "iso3": "CMR", "institution": "University of Dschang, Department of Soil Science; International Institute of Tropical Agriculture (IITA), Yaounde", "methodology": "Digital soil mapping (Random forest)", "n_samples": "1250", "sampling_period": "before and after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 101"},
  "CAN": {"country_name": "Canada", "iso3": "CAN", "institution": "Agriculture and Agri-Food Canada", "methodology": "Digital soil mapping (Mixed)", "n_samples": "48017", "sampling_period": "before and after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 102"},
  "CPV": {"country_name": "Cape Verde", "iso3": "CPV", "institution": "ISRIC World Soil Information", "methodology": "External product (SoilGrids 2.0)", "n_samples": "", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: External (soilgrids.org). Layer taken from SoilGrids 2.0 (Poggio et al. 2021), not a national submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 103"},
  "CAF": {"country_name": "Central African Republic", "iso3": "CAF", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Random forest)", "n_samples": "83", "sampling_period": "before 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 103"},
  "TCD": {"country_name": "Chad", "iso3": "TCD", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Support vector machines)", "n_samples": "5", "sampling_period": "before 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 104"},
  "CHL": {"country_name": "Chile", "iso3": "CHL", "institution": "Servicio Agricola y Ganadero, Departamento De Suelos", "methodology": "Digital soil mapping (Random forest)", "n_samples": "3258", "sampling_period": "after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 105"},
  "CHN": {"country_name": "China", "iso3": "CHN", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Support vector machines)", "n_samples": "1487", "sampling_period": "before and after 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 106"},
  "COL": {"country_name": "Colombia", "iso3": "COL", "institution": "Instituto Geografico Agustin Codazzi", "methodology": "Digital soil mapping (Regression Kriging)", "n_samples": "4329", "sampling_period": "before and after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 107"},
  "COM": {"country_name": "Comoros", "iso3": "COM", "institution": "ISRIC World Soil Information", "methodology": "External product (SoilGrids 2.0)", "n_samples": "", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: External (soilgrids.org). Layer taken from SoilGrids 2.0 (Poggio et al. 2021), not a national submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 108"},
  "COG": {"country_name": "Congo", "iso3": "COG", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Random forest)", "n_samples": "68", "sampling_period": "before and after 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 109"},
  "COK": {"country_name": "Cook Islands", "iso3": "COK", "institution": "ISRIC World Soil Information", "methodology": "External product (SoilGrids 2.0)", "n_samples": "", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: External (soilgrids.org). Layer taken from SoilGrids 2.0 (Poggio et al. 2021), not a national submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 110"},
  "CRI": {"country_name": "Costa Rica", "iso3": "CRI", "institution": "Instituto Nacional de Innovacion de Transferencia en Tecnologia (INTA); Centro de investigaciones Agronomicas, Universidad de Costa Rica", "methodology": "Digital soil mapping (Random forest)", "n_samples": "1518", "sampling_period": "before and after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 110"},
  "CIV": {"country_name": "Côte d'Ivoire", "iso3": "CIV", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Random forest)", "n_samples": "250", "sampling_period": "before 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 111"},
  "HRV": {"country_name": "Croatia", "iso3": "HRV", "institution": "ISRIC World Soil Information", "methodology": "External product (SoilGrids 2.0)", "n_samples": "", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: External (soilgrids.org). Layer taken from SoilGrids 2.0 (Poggio et al. 2021), not a national submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 112"},
  "CUB": {"country_name": "Cuba", "iso3": "CUB", "institution": "Instituto de Suelos, Ministerio de Agricultura", "methodology": "Digital soil mapping (Random forest)", "n_samples": "30886", "sampling_period": "before 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 112"},
  "CYP": {"country_name": "Cyprus", "iso3": "CYP", "institution": "European Soil Data Centre (ESDAC)", "methodology": "Digital soil mapping (Support vector machines)", "n_samples": "90", "sampling_period": "after 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 113"},
  "CZE": {"country_name": "Czech Republic", "iso3": "CZE", "institution": "Czech University of Life Sciences Prague", "methodology": "Digital soil mapping (Random forest)", "n_samples": "4169", "sampling_period": "before and after 1990", "gap_filled": "no", "notes": "Map source: Joint effort with GSP. Map produced jointly by the country and the GSP Secretariat.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 114"},
  "PRK": {"country_name": "Democratic People's Republic of Korea", "iso3": "PRK", "institution": "ISRIC World Soil Information", "methodology": "External product (SoilGrids 2.0)", "n_samples": "", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: External (soilgrids.org). Layer taken from SoilGrids 2.0 (Poggio et al. 2021), not a national submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 115"},
  "COD": {"country_name": "Democratic Republic of the Congo", "iso3": "COD", "institution": "Observatoire Satellital des Forets d'Afrique Centrale (OSFAC) / Universite de Kinshasa", "methodology": "Digital soil mapping (Random forest)", "n_samples": "773", "sampling_period": "before and after 1990", "gap_filled": "no", "notes": "Map source: Joint effort with GSP. Map produced jointly by the country and the GSP Secretariat.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 115"},
  "DNK": {"country_name": "Denmark", "iso3": "DNK", "institution": "Agroecology, Aarhus University", "methodology": "Digital soil mapping (Regression Kriging)", "n_samples": "46850", "sampling_period": "before and after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 116"},
  "DJI": {"country_name": "Djibouti", "iso3": "DJI", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Support vector machines)", "n_samples": "0", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 117"},
  "DMA": {"country_name": "Dominica", "iso3": "DMA", "institution": "ISRIC World Soil Information", "methodology": "External product (SoilGrids 2.0)", "n_samples": "", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: External (soilgrids.org). Layer taken from SoilGrids 2.0 (Poggio et al. 2021), not a national submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 118"},
  "DOM": {"country_name": "Dominican Republic", "iso3": "DOM", "institution": "Ministerio De Medio Ambiente y Recursos Naturales", "methodology": "Digital soil mapping (Random forest)", "n_samples": "120", "sampling_period": "after 1990", "gap_filled": "no", "notes": "Map source: Joint effort with GSP. Map produced jointly by the country and the GSP Secretariat.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 118"},
  "ECU": {"country_name": "Ecuador", "iso3": "ECU", "institution": "Ministerio de Agricultura y Ganaderia del Ecuador", "methodology": "Digital soil mapping (Regression Kriging)", "n_samples": "12861", "sampling_period": "after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 119"},
  "EGY": {"country_name": "Egypt", "iso3": "EGY", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Support vector machines)", "n_samples": "22", "sampling_period": "before and after 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 120"},
  "SLV": {"country_name": "El Salvador", "iso3": "SLV", "institution": "Ministerio de Medio Ambiente y Recursos Naturales (MARN)/ Centro Nacional de Tecnologia Agropecuaria y Forestal (CENTA)", "methodology": "Conventional upscaling (Geomatching / Class-matching)", "n_samples": "866", "sampling_period": "before and after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 121"},
  "GNQ": {"country_name": "Equatorial Guinea", "iso3": "GNQ", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Random forest)", "n_samples": "0", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 122"},
  "ERI": {"country_name": "Eritrea", "iso3": "ERI", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Support vector machines)", "n_samples": "0", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 123"},
  "EST": {"country_name": "Estonia", "iso3": "EST", "institution": "European Soil Data Centre (ESDAC)", "methodology": "Digital soil mapping (Support vector machines)", "n_samples": "220", "sampling_period": "after 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 124"},
  "SWZ": {"country_name": "Eswatini", "iso3": "SWZ", "institution": "Department of Geography, Environmental Science and Planning, University of Eswatini", "methodology": "Digital soil mapping (Random forest)", "n_samples": "91", "sampling_period": "after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 125"},
  "ETH": {"country_name": "Ethiopia", "iso3": "ETH", "institution": "Ministry of Agriculture and Natural Resources", "methodology": "Digital soil mapping (Random forest)", "n_samples": "58957", "sampling_period": "after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 126"},
  "FRO": {"country_name": "Faroe Islands", "iso3": "FRO", "institution": "European Soil Data Centre (ESDAC)", "methodology": "Digital soil mapping (Support vector machines)", "n_samples": "0", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 127"},
  "FJI": {"country_name": "Fiji", "iso3": "FJI", "institution": "ISRIC World Soil Information", "methodology": "External product (SoilGrids 2.0)", "n_samples": "", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: External (soilgrids.org). Layer taken from SoilGrids 2.0 (Poggio et al. 2021), not a national submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 128"},
  "FIN": {"country_name": "Finland", "iso3": "FIN", "institution": "Natural Resources Institute Finland", "methodology": "Conventional upscaling (Geomatching / Class-matching)", "n_samples": "2237", "sampling_period": "after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 128"},
  "FRA": {"country_name": "France", "iso3": "FRA", "institution": "Institut National de la Recherche Agronomique (INRA)", "methodology": "Digital soil mapping (Other)", "n_samples": "2952", "sampling_period": "", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 129"},
  "GAB": {"country_name": "Gabon", "iso3": "GAB", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Random forest)", "n_samples": "46", "sampling_period": "before 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 130"},
  "GMB": {"country_name": "Gambia", "iso3": "GMB", "institution": "Soil and Water Management Services Unit, Ministry of Agriculture", "methodology": "Digital soil mapping (Random forest)", "n_samples": "24", "sampling_period": "after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 131"},
  "GEO": {"country_name": "Georgia", "iso3": "GEO", "institution": "", "methodology": "external datasets", "n_samples": "0", "sampling_period": "external datasets", "gap_filled": "no", "notes": "Map source: Country submission. Report gives 'external datasets' for some data-specification fields.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 132"},
  "DEU": {"country_name": "Germany", "iso3": "DEU", "institution": "Thunen-Insitute of Forests Ecosystems, Thunen-Institutes of Climate-Smart Agriculture", "methodology": "Conventional upscaling (Geomatching / Class-matching)", "n_samples": "4863", "sampling_period": "after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 132"},
  "GHA": {"country_name": "Ghana", "iso3": "GHA", "institution": "CSIR-Soil Research Institute, Kwadaso-Kumasi, Ghana.", "methodology": "Digital soil mapping (Random forest)", "n_samples": "751", "sampling_period": "before and after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 133"},
  "GRC": {"country_name": "Greece", "iso3": "GRC", "institution": "European Soil Data Centre (ESDAC)", "methodology": "Digital soil mapping (Support vector machines)", "n_samples": "491", "sampling_period": "after 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 134"},
  "GRD": {"country_name": "Grenada", "iso3": "GRD", "institution": "ISRIC World Soil Information", "methodology": "External product (SoilGrids 2.0)", "n_samples": "", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: External (soilgrids.org). Layer taken from SoilGrids 2.0 (Poggio et al. 2021), not a national submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 135"},
  "GTM": {"country_name": "Guatemala", "iso3": "GTM", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Random forest)", "n_samples": "15", "sampling_period": "external datasets", "gap_filled": "yes", "notes": "Map source: GSP gap-filling. Report gives 'external datasets' for some data-specification fields.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 136"},
  "GIN": {"country_name": "Guinea", "iso3": "GIN", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Random forest)", "n_samples": "61", "sampling_period": "before 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 137"},
  "GNB": {"country_name": "Guinea-Bissau", "iso3": "GNB", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Random forest)", "n_samples": "17", "sampling_period": "before 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 138"},
  "GUY": {"country_name": "Guyana", "iso3": "GUY", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Support vector machines)", "n_samples": "43", "sampling_period": "before 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 139"},
  "HTI": {"country_name": "Haiti", "iso3": "HTI", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Other)", "n_samples": "135", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 140"},
  "HND": {"country_name": "Honduras", "iso3": "HND", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Random forest)", "n_samples": "7", "sampling_period": "external datasets", "gap_filled": "yes", "notes": "Map source: GSP gap-filling. Report gives 'external datasets' for some data-specification fields.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 140"},
  "HUN": {"country_name": "Hungary", "iso3": "HUN", "institution": "Institute for Soil Sciences and Agricultural Chemistry, Centre for Agricultural Research, Hungarian Academy of Sciences", "methodology": "Digital soil mapping (Random forest)", "n_samples": "1236", "sampling_period": "after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 142"},
  "ISL": {"country_name": "Iceland", "iso3": "ISL", "institution": "European Soil Data Centre (ESDAC)", "methodology": "Digital soil mapping (Support vector machines)", "n_samples": "0", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 142"},
  "IND": {"country_name": "India", "iso3": "IND", "institution": "National Bureau of Soil Survey and Land Use Planning, Nagpur; Indian Institute of soil Science, Bhopal", "methodology": "Digital soil mapping (Support vector machines)", "n_samples": "175993", "sampling_period": "after 1990", "gap_filled": "no", "notes": "Map source: Joint effort with GSP. Map produced jointly by the country and the GSP Secretariat.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 143"},
  "IDN": {"country_name": "Indonesia", "iso3": "IDN", "institution": "Indonesian Center for Agricultural Land Resource Research and Development", "methodology": "Conventional upscaling (Geomatching / Class-matching)", "n_samples": "15750", "sampling_period": "before and after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 144"},
  "IRN": {"country_name": "Iran (Islamic Republic of)", "iso3": "IRN", "institution": "Soil and Water Research Institute (SWRI)", "methodology": "Digital soil mapping (Random forest)", "n_samples": "954", "sampling_period": "before and after 1990", "gap_filled": "no", "notes": "Map source: Joint effort with GSP. Map produced jointly by the country and the GSP Secretariat.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 145"},
  "IRQ": {"country_name": "Iraq", "iso3": "IRQ", "institution": "Ministry of Agriculture", "methodology": "Digital soil mapping (Random forest)", "n_samples": "400", "sampling_period": "before and after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 146"},
  "IRL": {"country_name": "Ireland", "iso3": "IRL", "institution": "European Soil Data Centre (ESDAC)", "methodology": "Digital soil mapping (Support vector machines)", "n_samples": "233", "sampling_period": "after 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 147"},
  "ISR": {"country_name": "Israel", "iso3": "ISR", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Support vector machines)", "n_samples": "12", "sampling_period": "before 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 148"},
  "ITA": {"country_name": "Italy", "iso3": "ITA", "institution": "Research centre for agriculture and environment (CREA)", "methodology": "Digital soil mapping (Mixed)", "n_samples": "6748", "sampling_period": "after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 149"},
  "JAM": {"country_name": "Jamaica", "iso3": "JAM", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Random forest)", "n_samples": "77", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 150"},
  "JPN": {"country_name": "Japan", "iso3": "JPN", "institution": "Institute for Agro-Environmental Sciences (NARO); Forestry and Forest Products Research Institute", "methodology": "Conventional upscaling (Geomatching / Class-matching)", "n_samples": "6254", "sampling_period": "after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 151"},
  "JOR": {"country_name": "Jordan", "iso3": "JOR", "institution": "MOA", "methodology": "Digital soil mapping (Regression Kriging)", "n_samples": "1072", "sampling_period": "after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 152"},
  "KAZ": {"country_name": "Kazakhstan", "iso3": "KAZ", "institution": "Kazakh Research Institute of Soil Science and Agrochemistry named after U.U. Uspanov", "methodology": "Digital soil mapping (Random forest)", "n_samples": "502", "sampling_period": "before and after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 153"},
  "KEN": {"country_name": "Kenya", "iso3": "KEN", "institution": "Kenya Agricultural and Livestock Research Organization", "methodology": "Digital soil mapping (Other)", "n_samples": "2059", "sampling_period": "before and after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 154"},
  "KIR": {"country_name": "Kiribati", "iso3": "KIR", "institution": "ISRIC World Soil Information", "methodology": "External product (SoilGrids 2.0)", "n_samples": "", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: External (soilgrids.org). Layer taken from SoilGrids 2.0 (Poggio et al. 2021), not a national submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 155"},
  "KWT": {"country_name": "Kuwait", "iso3": "KWT", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Support vector machines)", "n_samples": "0", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 155"},
  "KGZ": {"country_name": "Kyrgyzstan", "iso3": "KGZ", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Random forest)", "n_samples": "0", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 156"},
  "LAO": {"country_name": "Lao People's Democratic Republic", "iso3": "LAO", "institution": "Ministry of Agriculture and Forestry of Laos", "methodology": "Digital soil mapping (Random forest)", "n_samples": "155", "sampling_period": "", "gap_filled": "no", "notes": "Map source: Joint effort with GSP. Map produced jointly by the country and the GSP Secretariat.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 157"},
  "LVA": {"country_name": "Latvia", "iso3": "LVA", "institution": "European Soil Data Centre (ESDAC)", "methodology": "Digital soil mapping (Support vector machines)", "n_samples": "349", "sampling_period": "after 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 158"},
  "LBN": {"country_name": "Lebanon", "iso3": "LBN", "institution": "Handler Institute: National Council for Scientific Research CNRS Lebanon", "methodology": "Digital soil mapping (Other)", "n_samples": "450", "sampling_period": "after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 159"},
  "LSO": {"country_name": "Lesotho", "iso3": "LSO", "institution": "Ministry of Forestry, Range and Soil Conservation", "methodology": "Digital soil mapping (Mixed)", "n_samples": "74", "sampling_period": "before 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 160"},
  "LBR": {"country_name": "Liberia", "iso3": "LBR", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Random forest)", "n_samples": "48", "sampling_period": "before and after 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 161"},
  "LBY": {"country_name": "Libya", "iso3": "LBY", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Support vector machines)", "n_samples": "14", "sampling_period": "before 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 162"},
  "LTU": {"country_name": "Lithuania", "iso3": "LTU", "institution": "European Soil Data Centre (ESDAC)", "methodology": "Digital soil mapping (Support vector machines)", "n_samples": "356", "sampling_period": "after 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 163"},
  "LUX": {"country_name": "Luxembourg", "iso3": "LUX", "institution": "Administration of agricultural technical services - Soil department", "methodology": "Digital soil mapping (Linear Models)", "n_samples": "3492", "sampling_period": "after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 164"},
  "MDG": {"country_name": "Madagascar", "iso3": "MDG", "institution": "Laboratoire des Radioisotopes, University of Antananarivo", "methodology": "Digital soil mapping (Random forest)", "n_samples": "1193", "sampling_period": "after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 165"},
  "MWI": {"country_name": "Malawi", "iso3": "MWI", "institution": "Department of Land Resources Conservation, Ministry of Agricul- ture, Irrigation and Water Development,", "methodology": "Digital soil mapping (Linear Models)", "n_samples": "4922", "sampling_period": "after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 166"},
  "MYS": {"country_name": "Malaysia", "iso3": "MYS", "institution": "ISRIC World Soil Information", "methodology": "External product (SoilGrids 2.0)", "n_samples": "", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: External (soilgrids.org). Layer taken from SoilGrids 2.0 (Poggio et al. 2021), not a national submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 166"},
  "MDV": {"country_name": "Maldives", "iso3": "MDV", "institution": "ISRIC World Soil Information", "methodology": "External product (SoilGrids 2.0)", "n_samples": "", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: External (soilgrids.org). Layer taken from SoilGrids 2.0 (Poggio et al. 2021), not a national submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 167"},
  "MLI": {"country_name": "Mali", "iso3": "MLI", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Support vector machines)", "n_samples": "667", "sampling_period": "before and after 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 167"},
  "MLT": {"country_name": "Malta", "iso3": "MLT", "institution": "European Soil Data Centre (ESDAC)", "methodology": "Digital soil mapping (Support vector machines)", "n_samples": "19", "sampling_period": "after 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 168"},
  "MHL": {"country_name": "Marshall Islands", "iso3": "MHL", "institution": "ISRIC World Soil Information", "methodology": "External product (SoilGrids 2.0)", "n_samples": "", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: External (soilgrids.org). Layer taken from SoilGrids 2.0 (Poggio et al. 2021), not a national submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 169"},
  "MRT": {"country_name": "Mauritania", "iso3": "MRT", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Support vector machines)", "n_samples": "11", "sampling_period": "before 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 170"},
  "MUS": {"country_name": "Mauritius", "iso3": "MUS", "institution": "ISRIC World Soil Information", "methodology": "External product (SoilGrids 2.0)", "n_samples": "", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: External (soilgrids.org). Layer taken from SoilGrids 2.0 (Poggio et al. 2021), not a national submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 171"},
  "MEX": {"country_name": "Mexico", "iso3": "MEX", "institution": "Instituto Nacional de Estadistica y Geografia (INEGI) with partners: CONAFOR, INIFAP, REDLABs, COLPOS, ECOSUR, FAO, University of Delaware, UNDP", "methodology": "Conventional upscaling, Digital soil mapping (Mixed)", "n_samples": "36015", "sampling_period": "before and after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 171"},
  "FSM": {"country_name": "Micronesia (Federated States of)", "iso3": "FSM", "institution": "ISRIC World Soil Information", "methodology": "External product (SoilGrids 2.0)", "n_samples": "", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: External (soilgrids.org). Layer taken from SoilGrids 2.0 (Poggio et al. 2021), not a national submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 173"},
  "MCO": {"country_name": "Monaco", "iso3": "MCO", "institution": "European Soil Data Centre (ESDAC)", "methodology": "Digital soil mapping (Support vector machines)", "n_samples": "0", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 173"},
  "MNG": {"country_name": "Mongolia", "iso3": "MNG", "institution": "Institue of Plant and Agriculture Science", "methodology": "Digital soil mapping (Random forest)", "n_samples": "512", "sampling_period": "after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 174"},
  "MNE": {"country_name": "Montenegro", "iso3": "MNE", "institution": "ISRIC World Soil Information", "methodology": "External product (SoilGrids 2.0)", "n_samples": "", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: External (soilgrids.org). Layer taken from SoilGrids 2.0 (Poggio et al. 2021), not a national submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 175"},
  "MAR": {"country_name": "Morocco", "iso3": "MAR", "institution": "INRA Morocco", "methodology": "Conventional upscaling, Digital soil mapping (Mixed)", "n_samples": "24000", "sampling_period": "before and after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 175"},
  "MOZ": {"country_name": "Mozambique", "iso3": "MOZ", "institution": "Mozambique Agrarian Reserch Institute", "methodology": "Digital soil mapping (Random forest)", "n_samples": "2427", "sampling_period": "before and after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 176"},
  "MMR": {"country_name": "Myanmar", "iso3": "MMR", "institution": "Ministry of Agriculture, Livestock and Irrigation (MoALI)", "methodology": "Digital soil mapping (Support vector machines)", "n_samples": "115", "sampling_period": "after 1990", "gap_filled": "no", "notes": "Map source: Joint effort with GSP. Map produced jointly by the country and the GSP Secretariat.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 177"},
  "NAM": {"country_name": "Namibia", "iso3": "NAM", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Random forest)", "n_samples": "56", "sampling_period": "before and after 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 178"},
  "NRU": {"country_name": "Nauru", "iso3": "NRU", "institution": "ISRIC World Soil Information", "methodology": "External product (SoilGrids 2.0)", "n_samples": "", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: External (soilgrids.org). Layer taken from SoilGrids 2.0 (Poggio et al. 2021), not a national submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 179"},
  "NPL": {"country_name": "Nepal", "iso3": "NPL", "institution": "Nepal Agricultural Research Council", "methodology": "Conventional upscaling (Geomatching / Class-matching)", "n_samples": "6000", "sampling_period": "after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 179"},
  "NLD": {"country_name": "Netherlands", "iso3": "NLD", "institution": "Wageningen University and Research, The Netherlands", "methodology": "Digital soil mapping (Regression Kriging)", "n_samples": "21210", "sampling_period": "after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 180"},
  "NZL": {"country_name": "New Zealand", "iso3": "NZL", "institution": "Landcare Research", "methodology": "Digital soil mapping (Linear Models)", "n_samples": "2050", "sampling_period": "before and after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 181"},
  "NIC": {"country_name": "Nicaragua", "iso3": "NIC", "institution": "Universidad Nacional Agraria", "methodology": "Digital soil mapping (Support vector machines)", "n_samples": "4000", "sampling_period": "before and after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 182"},
  "NER": {"country_name": "Niger", "iso3": "NER", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Support vector machines)", "n_samples": "478", "sampling_period": "before and after 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 182"},
  "NGA": {"country_name": "Nigeria", "iso3": "NGA", "institution": "Federal department of Agricultural Lands and Climate Change Management Service", "methodology": "Digital soil mapping (Linear Models)", "n_samples": "5545", "sampling_period": "before and after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 183"},
  "NIU": {"country_name": "Niue", "iso3": "NIU", "institution": "ISRIC World Soil Information", "methodology": "External product (SoilGrids 2.0)", "n_samples": "", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: External (soilgrids.org). Layer taken from SoilGrids 2.0 (Poggio et al. 2021), not a national submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 184"},
  "MKD": {"country_name": "North Macedonia", "iso3": "MKD", "institution": "Dusko Mukaetov", "methodology": "Digital soil mapping (Random forest)", "n_samples": "4300", "sampling_period": "before and after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 185"},
  "NOR": {"country_name": "Norway", "iso3": "NOR", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Mixed)", "n_samples": "3218", "sampling_period": "before and after 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 186"},
  "OMN": {"country_name": "Oman", "iso3": "OMN", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Support vector machines)", "n_samples": "9", "sampling_period": "before 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 186"},
  "PAK": {"country_name": "Pakistan", "iso3": "PAK", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Random forest)", "n_samples": "337", "sampling_period": "before 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 187"},
  "PLW": {"country_name": "Palau", "iso3": "PLW", "institution": "ISRIC World Soil Information", "methodology": "External product (SoilGrids 2.0)", "n_samples": "", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: External (soilgrids.org). Layer taken from SoilGrids 2.0 (Poggio et al. 2021), not a national submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 188"},
  "PAN": {"country_name": "Panama", "iso3": "PAN", "institution": "IDIAP", "methodology": "Digital soil mapping (Regression Kriging)", "n_samples": "837", "sampling_period": "after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 189"},
  "PNG": {"country_name": "Papua New Guinea", "iso3": "PNG", "institution": "ISRIC World Soil Information", "methodology": "External product (SoilGrids 2.0)", "n_samples": "", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: External (soilgrids.org). Layer taken from SoilGrids 2.0 (Poggio et al. 2021), not a national submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 190"},
  "PRY": {"country_name": "Paraguay", "iso3": "PRY", "institution": "Secretary of Environment SEAM", "methodology": "Digital soil mapping (Random forest)", "n_samples": "2768", "sampling_period": "after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 190"},
  "PER": {"country_name": "Peru", "iso3": "PER", "institution": "Ministerio de Agricultura y Riego", "methodology": "Digital soil mapping (Support vector machines)", "n_samples": "1010", "sampling_period": "before and after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 191"},
  "PHL": {"country_name": "Philippines", "iso3": "PHL", "institution": "Bureau of Soils and Water Management", "methodology": "Digital soil mapping (Other)", "n_samples": "500", "sampling_period": "before and after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 192"},
  "POL": {"country_name": "Poland", "iso3": "POL", "institution": "European Soil Data Centre (ESDAC)", "methodology": "Digital soil mapping (Support vector machines)", "n_samples": "1648", "sampling_period": "after 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 193"},
  "PRT": {"country_name": "Portugal", "iso3": "PRT", "institution": "European Soil Data Centre (ESDAC)", "methodology": "Digital soil mapping (Support vector machines)", "n_samples": "476", "sampling_period": "after 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 194"},
  "QAT": {"country_name": "Qatar", "iso3": "QAT", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Support vector machines)", "n_samples": "0", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 195"},
  "KOR": {"country_name": "Republic of Korea", "iso3": "KOR", "institution": "", "methodology": "external datasets", "n_samples": "0", "sampling_period": "external datasets", "gap_filled": "no", "notes": "Map source: Country submission. Report gives 'external datasets' for some data-specification fields.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 196"},
  "MDA": {"country_name": "Republic of Moldova", "iso3": "MDA", "institution": "Institute of Pedology, Agrochemistry and Soil Protection 'N. Dimo', Moldova", "methodology": "Conventional upscaling (Other)", "n_samples": "0", "sampling_period": "before 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 196"},
  "ROU": {"country_name": "Romania", "iso3": "ROU", "institution": "European Soil Data Centre (ESDAC)", "methodology": "Digital soil mapping (Support vector machines)", "n_samples": "1384", "sampling_period": "after 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 197"},
  "RUS": {"country_name": "Russian Federation", "iso3": "RUS", "institution": "M.V. Lomonosov Moscow State University soil science department, with partners", "methodology": "Conventional upscaling, Digital soil mapping (Mixed)", "n_samples": "150000", "sampling_period": "before and after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 198"},
  "RWA": {"country_name": "Rwanda", "iso3": "RWA", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Random forest)", "n_samples": "88", "sampling_period": "before and after 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 199"},
  "KNA": {"country_name": "Saint Kitts and Nevis", "iso3": "KNA", "institution": "ISRIC World Soil Information", "methodology": "External product (SoilGrids 2.0)", "n_samples": "", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: External (soilgrids.org). Layer taken from SoilGrids 2.0 (Poggio et al. 2021), not a national submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 200"},
  "LCA": {"country_name": "Saint Lucia", "iso3": "LCA", "institution": "ISRIC World Soil Information", "methodology": "External product (SoilGrids 2.0)", "n_samples": "", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: External (soilgrids.org). Layer taken from SoilGrids 2.0 (Poggio et al. 2021), not a national submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 201"},
  "VCT": {"country_name": "Saint Vincent and the Grenadines", "iso3": "VCT", "institution": "ISRIC World Soil Information", "methodology": "External product (SoilGrids 2.0)", "n_samples": "", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: External (soilgrids.org). Layer taken from SoilGrids 2.0 (Poggio et al. 2021), not a national submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 201"},
  "WSM": {"country_name": "Samoa", "iso3": "WSM", "institution": "ISRIC World Soil Information", "methodology": "External product (SoilGrids 2.0)", "n_samples": "", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: External (soilgrids.org). Layer taken from SoilGrids 2.0 (Poggio et al. 2021), not a national submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 202"},
  "STP": {"country_name": "Sao Tome e Principe", "iso3": "STP", "institution": "ISRIC World Soil Information", "methodology": "External product (SoilGrids 2.0)", "n_samples": "", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: External (soilgrids.org). Layer taken from SoilGrids 2.0 (Poggio et al. 2021), not a national submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 202"},
  "SAU": {"country_name": "Saudi Arabia", "iso3": "SAU", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Support vector machines)", "n_samples": "0", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 203"},
  "SEN": {"country_name": "Senegal", "iso3": "SEN", "institution": "Institut National de Pedologie", "methodology": "Digital soil mapping (Regression Kriging)", "n_samples": "678", "sampling_period": "after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 204"},
  "SRB": {"country_name": "Serbia", "iso3": "SRB", "institution": "ISRIC World Soil Information", "methodology": "External product (SoilGrids 2.0)", "n_samples": "", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: External (soilgrids.org). Layer taken from SoilGrids 2.0 (Poggio et al. 2021), not a national submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 204"},
  "SYC": {"country_name": "Seychelles", "iso3": "SYC", "institution": "ISRIC World Soil Information", "methodology": "External product (SoilGrids 2.0)", "n_samples": "", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: External (soilgrids.org). Layer taken from SoilGrids 2.0 (Poggio et al. 2021), not a national submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 205"},
  "SLE": {"country_name": "Sierra Leone", "iso3": "SLE", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Random forest)", "n_samples": "11", "sampling_period": "before 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 205"},
  "SGP": {"country_name": "Singapore", "iso3": "SGP", "institution": "ISRIC World Soil Information", "methodology": "External product (SoilGrids 2.0)", "n_samples": "", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: External (soilgrids.org). Layer taken from SoilGrids 2.0 (Poggio et al. 2021), not a national submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 206"},
  "SVK": {"country_name": "Slovakia", "iso3": "SVK", "institution": "National Agricultural and Food Centre, Soil Science and Conservation Research Institute; National Forestry Centre", "methodology": "Conventional upscaling (Geomatching / Class-matching)", "n_samples": "16748", "sampling_period": "before and after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 207"},
  "SVN": {"country_name": "Slovenia", "iso3": "SVN", "institution": "Agricultural institute of Slovenia", "methodology": "Conventional upscaling (Geomatching / Class-matching)", "n_samples": "1681", "sampling_period": "before and after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 208"},
  "SLB": {"country_name": "Solomon Islands", "iso3": "SLB", "institution": "ISRIC World Soil Information", "methodology": "External product (SoilGrids 2.0)", "n_samples": "", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: External (soilgrids.org). Layer taken from SoilGrids 2.0 (Poggio et al. 2021), not a national submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 208"},
  "SOM": {"country_name": "Somalia", "iso3": "SOM", "institution": "Somalia Water and Land Information Management (SWALIM)", "methodology": "Digital soil mapping (Support vector machines)", "n_samples": "257", "sampling_period": "after 1990", "gap_filled": "no", "notes": "Map source: Joint effort with GSP. Map produced jointly by the country and the GSP Secretariat.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 209"},
  "ZAF": {"country_name": "South Africa", "iso3": "ZAF", "institution": "Soil, Climate and Water (ARC-SCW)", "methodology": "Digital soil mapping (Support vector machines)", "n_samples": "11257", "sampling_period": "before and after 1990", "gap_filled": "no", "notes": "Map source: Joint effort with GSP. Map produced jointly by the country and the GSP Secretariat.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 210"},
  "SSD": {"country_name": "South Sudan", "iso3": "SSD", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Random forest)", "n_samples": "0", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 210"},
  "ESP": {"country_name": "Spain", "iso3": "ESP", "institution": "European Soil Data Centre (ESDAC)", "methodology": "Digital soil mapping (Support vector machines)", "n_samples": "2696", "sampling_period": "after 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 211"},
  "LKA": {"country_name": "Sri Lanka", "iso3": "LKA", "institution": "Natural Resources Management Centre, Department of Agriculture", "methodology": "Digital soil mapping (Linear Models)", "n_samples": "233", "sampling_period": "after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 212"},
  "SDN": {"country_name": "Sudan", "iso3": "SDN", "institution": "Land and Water Research Centre,", "methodology": "Digital soil mapping (Random forest)", "n_samples": "1584", "sampling_period": "before and after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 213"},
  "SUR": {"country_name": "Suriname", "iso3": "SUR", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Support vector machines)", "n_samples": "178", "sampling_period": "before 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 214"},
  "SWE": {"country_name": "Sweden", "iso3": "SWE", "institution": "Dep of Soil and Environment, SLU", "methodology": "Digital soil mapping (Other)", "n_samples": "19097", "sampling_period": "after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 215"},
  "CHE": {"country_name": "Switzerland", "iso3": "CHE", "institution": "Federal Office for the Environment, Soil and Biotechnology Division", "methodology": "Digital soil mapping (Mixed)", "n_samples": "1175", "sampling_period": "after 1990", "gap_filled": "no", "notes": "Map source: Joint effort with GSP. Map produced jointly by the country and the GSP Secretariat.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 216"},
  "SYR": {"country_name": "Syrian Arab Republic", "iso3": "SYR", "institution": "General Commission for Scientific Agriculture Research", "methodology": "Digital soil mapping (Support vector machines)", "n_samples": "1220", "sampling_period": "before 1990", "gap_filled": "no", "notes": "Map source: Joint effort with GSP. Map produced jointly by the country and the GSP Secretariat.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 217"},
  "TJK": {"country_name": "Tajikistan", "iso3": "TJK", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Random forest)", "n_samples": "21", "sampling_period": "before 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 218"},
  "TZA": {"country_name": "United Republic of Tanzania", "iso3": "TZA", "institution": "Agricultural Research Institute Mlingano", "methodology": "Digital soil mapping (Regression Kriging)", "n_samples": "3215", "sampling_period": "after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 219"},
  "THA": {"country_name": "Thailand", "iso3": "THA", "institution": "Land Development Department", "methodology": "Conventional upscaling (Geomatching / Class-matching)", "n_samples": "70000", "sampling_period": "after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 219"},
  "TLS": {"country_name": "Timor-Leste", "iso3": "TLS", "institution": "ISRIC World Soil Information", "methodology": "External product (SoilGrids 2.0)", "n_samples": "", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: External (soilgrids.org). Layer taken from SoilGrids 2.0 (Poggio et al. 2021), not a national submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 220"},
  "TGO": {"country_name": "Togo", "iso3": "TGO", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Random forest)", "n_samples": "9", "sampling_period": "before and after 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 221"},
  "TKL": {"country_name": "Tokelau", "iso3": "TKL", "institution": "ISRIC World Soil Information", "methodology": "External product (SoilGrids 2.0)", "n_samples": "", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: External (soilgrids.org). Layer taken from SoilGrids 2.0 (Poggio et al. 2021), not a national submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 222"},
  "TON": {"country_name": "Tonga", "iso3": "TON", "institution": "ISRIC World Soil Information", "methodology": "External product (SoilGrids 2.0)", "n_samples": "", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: External (soilgrids.org). Layer taken from SoilGrids 2.0 (Poggio et al. 2021), not a national submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 222"},
  "TTO": {"country_name": "Trinidad and Tobago", "iso3": "TTO", "institution": "University of The West Indies", "methodology": "Digital soil mapping (Geomatching / Class-matching)", "n_samples": "122", "sampling_period": "before 1990", "gap_filled": "no", "notes": "Map source: Joint effort with GSP. Map produced jointly by the country and the GSP Secretariat.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 222"},
  "TUN": {"country_name": "Tunisia", "iso3": "TUN", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Support vector machines)", "n_samples": "58", "sampling_period": "before and after 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 223"},
  "TUR": {"country_name": "Turkey", "iso3": "TUR", "institution": "General Directorate of Agricultural Research And Policies, Soil, Fertilizer and Water Resources Central Research Institute Ankara, TURKEY", "methodology": "Digital soil mapping (Regression Kriging)", "n_samples": "31800", "sampling_period": "after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 224"},
  "TKM": {"country_name": "Turkmenistan", "iso3": "TKM", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Random forest)", "n_samples": "0", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 225"},
  "TUV": {"country_name": "Tuvalu", "iso3": "TUV", "institution": "ISRIC World Soil Information", "methodology": "External product (SoilGrids 2.0)", "n_samples": "", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: External (soilgrids.org). Layer taken from SoilGrids 2.0 (Poggio et al. 2021), not a national submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 226"},
  "UGA": {"country_name": "Uganda", "iso3": "UGA", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Random forest)", "n_samples": "12", "sampling_period": "before 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 227"},
  "UKR": {"country_name": "Ukraine", "iso3": "UKR", "institution": "National Scientific Center 'Institute for Soil Science and Agrochemistry Research named after O.N. Sokolovsky' and contributors", "methodology": "Digital soil mapping (Mixed)", "n_samples": "3931", "sampling_period": "before and after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 228"},
  "ARE": {"country_name": "United Arab Emirates", "iso3": "ARE", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Support vector machines)", "n_samples": "0", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 229"},
  "GBR": {"country_name": "United Kingdom of Great Britain and Northern Ireland", "iso3": "GBR", "institution": "Cranfield University", "methodology": "Conventional upscaling (Geomatching / Class-matching)", "n_samples": "17421", "sampling_period": "before and after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 230"},
  "USA": {"country_name": "United States of America", "iso3": "USA", "institution": "Natural Resource Conservation Service", "methodology": "Conventional upscaling (Geomatching / Class-matching)", "n_samples": "10000", "sampling_period": "before and after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 230"},
  "URY": {"country_name": "Uruguay", "iso3": "URY", "institution": "Direccion General de Recursos Naturales", "methodology": "Digital soil mapping (Regression Kriging)", "n_samples": "160", "sampling_period": "before 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 231"},
  "UZB": {"country_name": "Uzbekistan", "iso3": "UZB", "institution": "UZGIP Design and Research Institute", "methodology": "Digital soil mapping (Random forest)", "n_samples": "4969", "sampling_period": "after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 232"},
  "VUT": {"country_name": "Vanuatu", "iso3": "VUT", "institution": "ISRIC World Soil Information", "methodology": "External product (SoilGrids 2.0)", "n_samples": "", "sampling_period": "", "gap_filled": "yes", "notes": "Map source: External (soilgrids.org). Layer taken from SoilGrids 2.0 (Poggio et al. 2021), not a national submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 233"},
  "VEN": {"country_name": "Venezuela (Bolivarian Republic of)", "iso3": "VEN", "institution": "Sociedad Venezolana de la Ciencia del Suelo (SVCS)", "methodology": "Digital soil mapping (Random forest)", "n_samples": "310", "sampling_period": "before and after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 234"},
  "VNM": {"country_name": "Viet Nam", "iso3": "VNM", "institution": "Soils and Fertilizers Research Institute", "methodology": "Digital soil mapping (Random forest)", "n_samples": "1024", "sampling_period": "after 1990", "gap_filled": "no", "notes": "Map source: Country submission.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 235"},
  "YEM": {"country_name": "Yemen", "iso3": "YEM", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Support vector machines)", "n_samples": "270", "sampling_period": "before 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 235"},
  "ZMB": {"country_name": "Zambia", "iso3": "ZMB", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Random forest)", "n_samples": "460", "sampling_period": "before 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 236"},
  "ZWE": {"country_name": "Zimbabwe", "iso3": "ZWE", "institution": "Global Soil Partnership", "methodology": "Digital soil mapping (Random forest)", "n_samples": "179", "sampling_period": "before and after 1990", "gap_filled": "yes", "notes": "Map source: GSP gap-filling.", "source": "GSOCmap v1.6 Technical Report (FAO 2022), Annex D, p. 237"},
};

// Index by country name as well, so formatGSOC accepts either.
var BY_NAME = {};
Object.keys(META).forEach(function (k) {
  BY_NAME[META[k].country_name.toLowerCase()] = META[k];
});

/**
 * One-line human-readable summary for a country.
 * @param {string} iso3OrName ISO3 code (any case) or country name.
 * @return {string|null} Summary string, or null when absent.
 */
function addCommas(n) {
  return String(n).replace(/\B(?=(\d{3})+(?!\d))/g, ',');
}

// The report uses 'external datasets' as a filler value in some specification
// fields; it is not information, so it is never displayed.
function cleanField(v) {
  if (!v || v === 'external datasets') return '';
  var s = String(v);
  return s.length > 90 ? s.slice(0, 87) + '...' : s;
}

function lookup(iso3OrName) {
  if (!iso3OrName) return null;
  var key = String(iso3OrName).trim();
  return META[key.toUpperCase()] || BY_NAME[key.toLowerCase()] || null;
}

function formatGSOC(iso3OrName) {
  var m = lookup(iso3OrName);
  if (!m) return null;
  var parts = [m.country_name + " (GSOCmap v1.6)"];
  parts.push(m.gap_filled === "yes" ? "gap-filled: yes" : "gap-filled: no");
  var meth = cleanField(m.methodology);
  if (meth) parts.push(meth);
  if (m.n_samples !== "" && m.n_samples !== "0") parts.push(addCommas(m.n_samples) + " samples");
  var per = cleanField(m.sampling_period);
  if (per) parts.push("period: " + per);
  var inst = cleanField(m.institution);
  if (inst) parts.push(inst);
  return parts.join("; ");
}

/**
 * One-or-two-sentence quality summary for the app's "Soil data quality"
 * expander. caution=true marks tiles that are not national submissions.
 * @param {string} iso3OrName
 * @return {Object|null} {caution: boolean, text: string}
 */
function briefGSOC(iso3OrName) {
  var m = lookup(iso3OrName);
  if (!m) return null;
  var name = m.country_name;
  var n = (m.n_samples !== '' && m.n_samples !== '0') ? addCommas(m.n_samples) : null;
  if (m.notes.indexOf('External') !== -1) {
    return {caution: true, text: name + "'s tile in GSOCmap is taken from SoilGrids 2.0, " +
            'not a national soil map.'};
  }
  if (m.notes.indexOf('GSP gap-filling') !== -1) {
    var pre = (m.sampling_period === 'before 1990') ? ', all collected before 1990,' : '';
    return {caution: true, text: name + "'s tile in GSOCmap was modelled by the Global " +
            'Soil Partnership from ' + (n ? n + ' field samples' + pre : 'very few field samples') +
            ' and is not a national soil map.'};
  }
  var joint = m.notes.indexOf('Joint effort') !== -1;
  return {caution: false, text: name + "'s tile in GSOCmap is a national soil map" +
          (joint ? ' produced jointly with the Global Soil Partnership' : '') +
          (n ? ', built from ' + n + ' samples.' : '.')};
}

exports.META = META;
exports.formatGSOC = formatGSOC;
exports.briefGSOC = briefGSOC;
