// Forest Soil Carbon App
var APP_VERSION = "0.7.7-alpha";

// Changelog: see CHANGELOG.md

// AIM: area-weighted mean soil organic carbon (SOC) in forest, per country,
//      for FAO FRA reporting and gap-filling.
//
// Method: forest area per pixel x SOC stock per hectare, summed per country,
//         divided by summed forest area. See docs/scope.md.
//
// GEE path: users/andyarnellgee/apps:forest_soil_carbon
// Source:   https://github.com/andyarnell/forestsoilcarbon

print('Forest Soil Carbon v' + APP_VERSION);

// Set to true when publishing as a GEE App. Export.table.toDrive silently does
// nothing in a published app, so the Drive-export button is hidden and only the
// in-app CSV download link is offered.
var IS_PUBLISHED_APP = false;

// =============================================================================
// MODULES
// gaulLut and fraStats are shared with the Primary Forest Finder toolset and
// live in github.com/andyarnell/primaryforestfinder/modules -- do not copy
// them in here. gsocMeta and fraSoc are THIS repo's data modules (modules/,
// regenerated by tools/); upload them to the same GEE modules path.
// =============================================================================

var gaulLut = require("users/andyarnellgee/apps:modules/gaulLut.js");
var fraStats = require("users/andyarnellgee/apps:modules/fraStats.js");
var gsocMeta = require("users/andyarnellgee/apps:modules/gsocMeta.js");
var fraSoc = require("users/andyarnellgee/apps:modules/fraSoc.js");

// =============================================================================
// CONSTANTS
// =============================================================================

var GAUL_L0_ASSET = 'projects/sat-io/open-datasets/FAO/GAUL/GAUL_2024_L0';

var GLOBAL_OPTION = 'Global (all countries)';
var CUSTOM_KEY = 'custom';

// Analysis scale in metres. Always passed explicitly to reducers. 'native'
// resolves at run time to the SOIL CARBON layer's own grid, read once from the
// asset (GSOCmap: 30 arc-sec, ~927.7 m -- the scale of the original 2024
// gap-filling runs; SoilGrids: 250 m). Carbon is the layer whose native grid
// matters: sampling it coarser goes through GEE's mean pyramids and averages
// away the within-cell detail exactly where the forest weighting needs it,
// while the forest FRACTION layers replicate to finer grids without error
// (and pixelArea keeps the areas exact at any scale).
var DEFAULT_SCALE = 1000;
var NATIVE_SCALE_KEY = 'native';
var SCALE_OPTIONS = ['1000', '500', '250', '100'];

// Year used for the FRA comparison line. fraStats covers 1990/2000/2010/2015/2020.
var FRA_YEAR = 2020;

// Reported-to-FRA reference values shown beside the estimate. Country-level
// reference data rather than a selectable dataset, so it lives here and not in
// the dataset configs. Soil carbon comes ISO3-keyed from fraSoc; forest area
// comes from the name-keyed fraStats tables.
var FRA_REPORTED = {cycle: 'FRA 2025', year: FRA_YEAR};

// GAUL includes disputed and placeholder territories with non-standard ISO3
// codes beginning with a lowercase 'x'. Excluded from country tables.
var DISPUTED_ISO3_PREFIX = 'x';

// Below this, the soil carbon layer has enough gaps over forest that the mean
// is not representative and the results panel says so.
var LOW_COVERAGE_WARN_PC = 90;

// =============================================================================
// QUANTITIES
//
// What the pixel values physically are. This is the primitive that decides what
// the app is allowed to report:
//
//   'stock'          mass per area (t C/ha). Adds up over area, so both the
//                    MEAN and the TOTAL are valid. This is what FRA asks for.
//   'concentration'  mass fraction (g/kg). The area-weighted MEAN is a valid
//                    quantity; the TOTAL is not -- summing a concentration over
//                    area gives g/kg*ha, which is not a thing. No total shown.
//   'unknown'        the user has not said. Nothing is computed.
//
// Units live here and are never stored per dataset, so a config cannot claim to
// be a stock measured in g/kg. `col` is the suffix on the results column and
// the CSV header, so a number cannot leave the app without its unit attached.
// =============================================================================

var QUANTITY = {
  stock:         {unit: 't C/ha', col: 't_ha',    summable: true},
  concentration: {unit: 'g/kg',   col: 'g_kg',    summable: false},
  unknown:       {unit: '?',      col: 'unknown', summable: false}
};

// =============================================================================
// SOIL DEPTH
//
// The depth dropdown drives which soil carbon layers are offered: only layers
// whose `depth_cm` matches the selected depth appear. Adding a deeper product
// later means adding a dataset entry with that depth_cm -- the option becomes
// selectable on its own.
//
// FRA does NOT mandate a depth. Both FRA 2020 and FRA 2025 define soil carbon
// as "organic carbon in mineral and organic soils (including peat) to a
// specified depth chosen by the country and applied consistently through the
// time series", and the reporting table has a field "Soil depth (cm) used for
// soil carbon". The forest-area-weighted mean depth countries actually report
// is 41 cm (FRA 2025): 30 cm Asia/Oceania, 32 Europe, 34 South America,
// 41 Africa, 70 North and Central America.
//
// So 0-30 cm is what the global data supports, NOT what FRA asks for. A country
// reporting at another depth must say so, and must not silently swap depth
// between cycles. See docs/scope.md.
// =============================================================================

var DEPTH_OPTIONS = [
  {value: '0-30', label: '0-30 cm'},
  {value: '0-100', label: '0-100 cm'},
  {value: 'other', label: 'Other / not stated'}
];

// =============================================================================
// SOIL CARBON DATASETS
// Add a layer by adding one object here -- there is no dataset-specific logic
// anywhere else in this file.
//
//   quantity      key into QUANTITY above. Decides what gets reported.
//   scale_factor  multiplier applied to raw pixel values to reach that unit
//   depth_cm      the depth the values represent; must match a DEPTH_OPTIONS
//                 value to be offered
//   band          band name, or null for a single-band image
//
// Only layers that are already a single band at a stated depth are offered.
// Products that split the profile into intervals or report at point depths
// (SoilGrids soc_mean, OpenLandMap) are deliberately not included -- they are
// concentrations, which cannot be reported as the FRA figure, and both are
// superseded by SoilGrids ocs_mean. See docs/soil_carbon_datasets_review.md.
// =============================================================================

var SOC_DATASETS = [
  {
    key: 'gsoc_1_5',
    label: 'GSOCmap 1.5 (FAO) - 0-30 cm stock',
    short_label: 'GSOCmap v1.5 soil',
    asset: 'projects/ee-andyarnellgee/assets/crosscutting/GSOCmap1_5_0',
    band: null,                  // single-band image
    quantity: 'stock',
    scale_factor: 1,
    depth_cm: '0-30',
    native_resolution_m: 1000,
    citation: 'FAO & ITPS (2022) Global Soil Organic Carbon Map (GSOCmap) v1.5. FAO, Rome.',
    // Per-country provenance from the GSOCmap v1.6 technical report, Annex D
    // (modules/gsocMeta.js). NB the report describes v1.6 while this asset is
    // v1.5: national submissions largely carry over, but the 39 entries taken
    // from SoilGrids 2.0 are v1.6-specific. Swap the asset to v1.6 to align.
    meta_format: gsocMeta.formatGSOC,
    meta_brief: gsocMeta.briefGSOC,
    meta_missing: 'No country entry in the GSOCmap v1.6 technical report.'
  },
  {
    key: 'soilgrids_ocs',
    label: 'SoilGrids 2.0 (ISRIC) - 0-30 cm stock',
    short_label: 'SoilGrids 2.0 soil',
    asset: 'projects/soilgrids-isric/ocs_mean',
    band: 'ocs_0-30cm_mean',
    // ISRIC stores ocs ALREADY in t/ha. Their published "conversion factor 10"
    // converts t/ha to kg/m2, the other direction. Do not apply 0.1 here -- it
    // would report every figure 10x too low.
    quantity: 'stock',
    scale_factor: 1,
    depth_cm: '0-30',
    native_resolution_m: 250,
    citation: 'Poggio, L. et al. (2021) SoilGrids 2.0. SOIL 7, 217-240.'
  }
];

// =============================================================================
// FOREST DATASETS
//
//   type 'prop_aggregated'  1 km images pre-aggregated from a finer source.
//                           `prop_band` is the fraction of the pixel that is
//                           forest (0-1). Area comes from ee.Image.pixelArea()
//                           like every other type: the assets do carry their
//                           own pixel_area_km band (HECTARES despite the name)
//                           but the app must not read it -- a stored
//                           per-native-pixel area summed at a finer analysis
//                           scale multiplies every total (see buildForestArea).
//   type 'binary'           a mask; `threshold` is the value above which a
//                           pixel counts as forest. Area comes from
//                           ee.Image.pixelArea() at the analysis scale.
//   type 'fraction'         values already 0-1 fractional cover.
// =============================================================================

var FOREST_DATASETS = [
  {
    key: 'jrc_gfc_2020',
    label: 'JRC Global Forest Cover 2020',
    short_label: 'JRC forest 2020',
    asset: 'projects/ee-andyarnellgee/assets/misc/team_fra_support/jrc_gfc2020_prop_in_1km_aggr',
    type: 'prop_aggregated',
    prop_band: 'prop_cover_2020',
    year: 2020,
    citation: 'Bourgoin, C. et al. (2024) Global map of forest cover 2020 v2. European Commission JRC.'
  },
  {
    key: 'hansen_10pc_2020',
    label: 'Hansen GFC, >10% tree cover, 2020',
    short_label: 'Hansen >10% forest 2020',
    asset: 'projects/ee-andyarnellgee/assets/misc/team_fra_support/hansen_10pc_cover_2020_pixel_prop_in_1km_aggr',
    type: 'prop_aggregated',
    prop_band: 'prop_cover_2020',
    year: 2020,
    citation: 'Hansen, M.C. et al. (2013) High-resolution global maps of 21st-century forest cover change. Science 342, 850-853.'
  },
  {
    key: 'hansen_20pc_2020',
    label: 'Hansen GFC, >20% tree cover, 2020',
    short_label: 'Hansen >20% forest 2020',
    asset: 'projects/ee-andyarnellgee/assets/misc/team_fra_support/hansen_20pc_cover_2020_pixel_prop_in_1km_aggr',
    type: 'prop_aggregated',
    prop_band: 'prop_cover_2020',
    year: 2020,
    citation: 'Hansen, M.C. et al. (2013) Science 342, 850-853.'
  },
  {
    key: 'globland_2020',
    label: 'GlobeLand30 forest 2020',
    short_label: 'GlobeLand30 forest 2020',
    asset: 'projects/ee-andyarnellgee/assets/misc/team_fra_support/globland_forest__2020_pixel_prop_in_1km_aggr',
    type: 'prop_aggregated',
    prop_band: 'prop_cover_2020',
    year: 2020,
    citation: 'Chen, J. et al. (2015) Global land cover mapping at 30 m resolution. ISPRS J. Photogramm. 103, 7-27.'
  }
];

// =============================================================================
// VISUALISATION PARAMETERS
// =============================================================================

var SOC_STOCK_VIS = {min: 0, max: 200, palette: ['#ffffcc', '#fed976', '#fd8d3c', '#7f2704']};
var SOC_CONC_VIS = {min: 0, max: 60, palette: ['#ffffcc', '#fed976', '#fd8d3c', '#7f2704']};
var FOREST_VIS = {min: 0, max: 1, palette: ['white', '#1b7837']};
var SOC_IN_FOREST_VIS = {min: 0, max: 100, palette: ['#f7f4f9', '#c994c7', '#980043']};

var HINT_STYLE = {fontSize: '10px', color: '#666', margin: '0 0 4px 4px'};
var BODY_STYLE = {fontSize: '11px', margin: '2px 0 2px 4px'};
var HEADING_STYLE = {fontSize: '13px', fontWeight: 'bold', margin: '4px 0 2px 4px'};
var LINK_STYLE = {fontSize: '11px', color: 'blue', textDecoration: 'underline', margin: '4px 0 2px 4px'};
var WARN_STYLE = {fontSize: '11px', color: '#b00020', margin: '2px 0 2px 4px'};
var KICKER_STYLE = {fontSize: '11px', color: '#666', margin: '8px 0 0 4px'};
var EST_VALUE_STYLE = {fontSize: '14px', fontWeight: 'bold', margin: '2px 0 2px 4px'};
var BLOCKHEAD_STYLE = {fontSize: '12px', fontWeight: 'bold', margin: '12px 0 2px 4px'};
// Tint for the Soil data quality toggle when the tile is not a national
// submission or coverage is low.
var AMBER_BTN = '#fff4e5';

// =============================================================================
// STATE
// =============================================================================

var appState = {
  ui: {
    forestCollapsed: false,
    socCollapsed: false,
    optionsCollapsed: true,
    qualityCollapsed: true,
    detailsCollapsed: true
  }
};

// The current selection, rebuilt on every widget change and on Run. The map,
// the pixel inspector and the statistics all read from it, so they can never
// describe different selections. Replaces the old lastRun freeze: results for
// an abandoned selection are cleared, not kept.
var currentCtx = null;

// Guards the results-clearing while startup handlers fire.
var uiReady = false;

// The click marker, kept so each click replaces the previous one instead of
// stacking layers.
var markerLayer = null;

// Built once from GAUL_LUT so ISO3 results can be joined to the name-keyed
// fraStats tables, and country names to the ISO3-keyed gsocMeta table.
// gaulLut exports neither mapping.
var iso3ToName = {};
var nameToIso3 = {};
(function () {
  var codes = Object.keys(gaulLut.GAUL_LUT);
  codes.forEach(function (code) {
    var entry = gaulLut.GAUL_LUT[code];
    iso3ToName[entry.iso3] = entry.name;
    nameToIso3[entry.name] = entry.iso3;
  });
})();

// =============================================================================
// DATA PREPARATION
// =============================================================================

/**
 * Look up a dataset config by its key.
 * @param {Array<Object>} list  SOC_DATASETS or FOREST_DATASETS
 * @param {string} key
 * @return {Object|null}
 */
function getDatasetByKey(list, key) {
  var found = null;
  list.forEach(function (d) {
    if (d.key === key) { found = d; }
  });
  return found;
}

/**
 * Soil carbon layers available at a given depth.
 * @param {string} depth  a DEPTH_OPTIONS value
 * @return {Array<Object>}
 */
function socDatasetsForDepth(depth) {
  return SOC_DATASETS.filter(function (d) { return d.depth_cm === depth; });
}

/**
 * Build a single-band soil carbon image in the unit its quantity implies.
 * @param {Object} cfg  a SOC_DATASETS-shaped config
 * @return {ee.Image} band 'soc_value' -- deliberately unit-agnostic, because
 *     the band may hold a stock or a concentration depending on cfg.quantity
 */
function buildSocImage(cfg) {
  var img = ee.Image(cfg.asset);
  img = cfg.band ? img.select([cfg.band]) : img.select([0]);
  return img.multiply(cfg.scale_factor).rename('soc_value');
}

/**
 * Build forest area per pixel, in hectares.
 * @param {Object} cfg  a FOREST_DATASETS-shaped config
 * @return {ee.Image} band 'forest_area_ha'
 */
function buildForestArea(cfg) {
  // Fraction x ee.Image.pixelArea() for EVERY type, including prop_aggregated.
  // The aggregated assets carry their own per-pixel area band, but summing a
  // stored per-native-pixel value at a finer analysis scale counts each native
  // pixel (native/scale)^2 times -- at 500 m that tripled every country's
  // forest area while leaving the mean untouched (both sums inflate together).
  // pixelArea() is per-OUTPUT-pixel at the analysis scale, so it cannot.
  var pixelHa = ee.Image.pixelArea().divide(10000);
  return buildForestFraction(cfg).multiply(pixelHa).rename('forest_area_ha');
}

/**
 * Forest cover fraction, 0-1.
 * @param {Object} cfg  a FOREST_DATASETS-shaped config
 * @return {ee.Image}
 */
function buildForestFraction(cfg) {
  if (cfg.type === 'prop_aggregated') {
    return ee.Image(cfg.asset).select([cfg.prop_band]);
  }
  var img = ee.Image(cfg.asset);
  img = cfg.band ? img.select([cfg.band]) : img.select([0]);
  if (cfg.type === 'binary') {
    var threshold = (cfg.threshold === undefined || cfg.threshold === null) ? 0 : cfg.threshold;
    return img.gt(threshold);
  }
  return img.clamp(0, 1);
}

/**
 * Country polygons to summarise over.
 * @param {string} countryName  a GAUL name, or GLOBAL_OPTION
 * @return {ee.FeatureCollection} GAUL 2024 L0 features
 */
function getRegions(countryName) {
  var all = ee.FeatureCollection(GAUL_L0_ASSET);
  if (countryName === GLOBAL_OPTION) {
    // Drop disputed / placeholder territories from FRA country tables
    return all.filter(ee.Filter.stringStartsWith('iso3_code', DISPUTED_ISO3_PREFIX).not());
  }
  return all.filter(ee.Filter.eq('gaul0_code', gaulLut.nameToCode(countryName)));
}

// =============================================================================
// STATISTICS
// GAUL Level 0 is one feature per country, so unlike the original UN BNDA
// script no reduceColumns grouping step is needed to collapse multi-polygon
// countries -- reduceRegions already returns one row per country.
// =============================================================================

/**
 * Per-country forest area, carbon in forest, and the area-weighted mean.
 *
 * Forest pixels with no soil data are excluded from BOTH the numerator and the
 * denominator. Reducing forest area as its own band would leave its mask
 * independent of the soil layer's, counting those pixels in the denominator
 * only and biasing the mean low wherever the soil layer has gaps -- which
 * GSOCmap does. `forest_area_ha` is still reported separately so the coverage
 * can be shown.
 *
 * @param {ee.Image} socImage        band 'soc_value'
 * @param {ee.Image} forestAreaImage band 'forest_area_ha'
 * @param {ee.FeatureCollection} regions
 * @param {number} scale  metres
 * @param {Object} socCfg  used for the quantity-dependent column name
 * @return {ee.FeatureCollection} geometry-free features, one per country
 */
function computeCountryStats(socImage, forestAreaImage, regions, scale, socCfg) {
  var meanColumn = meanColumnName(socCfg);

  var forestWithSoc = forestAreaImage.updateMask(socImage.mask())
                                     .rename('forest_area_with_soc_ha');
  var weighted = socImage.multiply(forestWithSoc).rename('soc_weighted_sum');

  var summed = weighted
    .addBands(forestWithSoc)
    .addBands(forestAreaImage)
    .reduceRegions({
      collection: regions,
      reducer: ee.Reducer.sum(),
      scale: scale,
      tileScale: 4
    });

  return summed.map(function (f) {
    var areaAll = numberOrZero(f.get('forest_area_ha'));
    var areaWithSoc = numberOrZero(f.get('forest_area_with_soc_ha'));
    var weightedSum = numberOrZero(f.get('soc_weighted_sum'));

    var props = {
      iso3: f.get('iso3_code'),
      country: f.get('gaul0_name'),
      forest_area_ha: areaAll,
      forest_area_with_soc_ha: areaWithSoc,
      soc_data_coverage_pc: ee.Algorithms.If(
        areaAll.gt(0), areaWithSoc.divide(areaAll).multiply(100), null),
      soc_in_forest_total: weightedSum
    };
    props[meanColumn] = ee.Algorithms.If(
      areaWithSoc.gt(0), weightedSum.divide(areaWithSoc), null);

    return ee.Feature(null, props);
  });
}

/**
 * @param {*} value  a possibly-null feature property
 * @return {ee.Number}
 */
function numberOrZero(value) {
  return ee.Number(ee.Algorithms.If(value, value, 0));
}

/**
 * The results/CSV column holding the mean, with its unit baked into the name so
 * the number cannot travel without it.
 * @param {Object} socCfg
 * @return {string} e.g. 'mean_soc_t_ha'
 */
function meanColumnName(socCfg) {
  return 'mean_soc_' + QUANTITY[socCfg.quantity].col;
}

/**
 * Collapse a stats collection to totals across all its rows.
 * @param {ee.FeatureCollection} statsFc
 * @param {Object} socCfg
 * @return {ee.Dictionary}
 */
function computeTotals(statsFc, socCfg) {
  var sums = ee.Dictionary(statsFc.reduceColumns({
    reducer: ee.Reducer.sum().repeat(3),
    selectors: ['soc_in_forest_total', 'forest_area_with_soc_ha', 'forest_area_ha']
  }));
  var values = ee.List(sums.get('sum'));
  var weightedSum = ee.Number(values.get(0));
  var areaWithSoc = ee.Number(values.get(1));
  var areaAll = ee.Number(values.get(2));

  return ee.Dictionary({
    soc_in_forest_total: weightedSum,
    forest_area_ha: areaAll,
    forest_area_with_soc_ha: areaWithSoc,
    coverage_pc: ee.Algorithms.If(
      areaAll.gt(0), areaWithSoc.divide(areaAll).multiply(100), null),
    mean: ee.Algorithms.If(
      areaWithSoc.gt(0), weightedSum.divide(areaWithSoc), null)
  });
}

// =============================================================================
// FORMATTING HELPERS
// =============================================================================

function withCommas(value) {
  return value.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ',');
}

/**
 * @param {number} value
 * @param {number} decimals
 * @return {string} thousands-separated, or 'n/a' for null
 */
function formatNumber(value, decimals) {
  if (value === null || value === undefined) { return 'n/a'; }
  var fixed = Number(value).toFixed(decimals);
  var parts = fixed.split('.');
  return parts.length > 1 ? withCommas(parts[0]) + '.' + parts[1] : withCommas(parts[0]);
}

// =============================================================================
// UI - REUSABLE PIECES
// =============================================================================

/**
 * A collapsible left-panel section in the pff_layout style.
 * @param {string} title
 * @param {Array} widgets
 * @param {string} stateKey  key in appState.ui
 * @return {ui.Panel}
 */
function makeCollapsible(title, widgets, stateKey, btnBackground) {
  var content = ui.Panel({
    widgets: widgets,
    style: {shown: !appState.ui[stateKey], padding: '4px'}
  });

  var glyph = function () { return appState.ui[stateKey] ? '▶ ' : '▼ '; };

  var toggle = ui.Button({
    label: glyph() + title,
    onClick: function () {
      appState.ui[stateKey] = !appState.ui[stateKey];
      content.style().set({shown: !appState.ui[stateKey]});
      toggle.setLabel(glyph() + title);
    },
    style: {
      stretch: 'horizontal', textAlign: 'left', padding: '3px 6px',
      margin: '1px', fontSize: '12px', backgroundColor: btnBackground || '#f0f0f0'
    }
  });

  return ui.Panel({
    widgets: [toggle, content],
    layout: ui.Panel.Layout.flow('vertical')
  });
}

// =============================================================================
// UI - SOIL CARBON SECTION
// The dataset list is rebuilt whenever the depth changes, so only layers that
// actually represent the selected depth can be picked.
// =============================================================================

var socSelect = ui.Select({
  items: [],
  style: {stretch: 'horizontal', margin: '2px 4px'},
  onChange: function (key) {
    socCustomPanel.style().set({shown: key === CUSTOM_KEY});
    socNoteLabel.setValue(describeSocChoice(key));
    updatePreview();
    clearResultsForNewSelection();
  }
});

var socNoteLabel = ui.Label('', HINT_STYLE);

var socAssetBox = ui.Textbox({
  placeholder: 'projects/your-project/assets/national_soc_map',
  style: {stretch: 'horizontal', margin: '2px 4px', fontSize: '11px'},
  onChange: function () { updatePreview(); clearResultsForNewSelection(); }
});

var socBandBox = ui.Textbox({
  placeholder: 'band name (blank = first band)',
  style: {stretch: 'horizontal', margin: '2px 4px', fontSize: '11px'},
  onChange: function () { updatePreview(); clearResultsForNewSelection(); }
});

// Defaults to 'unknown' on purpose. A user who ignores this must not get a
// confident t C/ha figure computed from a layer of undeclared type.
var socQuantitySelect = ui.Select({
  items: [
    {label: '- I do not know -', value: 'unknown'},
    {label: 'Stock: tonnes of carbon per hectare (t C/ha)', value: 'stock'},
    {label: 'Concentration: grams of carbon per kg of soil (g/kg)', value: 'concentration'}
  ],
  value: 'unknown',
  style: {stretch: 'horizontal', margin: '2px 4px'},
  onChange: function () { updatePreview(); clearResultsForNewSelection(); }
});

var socScaleFactorBox = ui.Textbox({
  value: '1',
  style: {stretch: 'horizontal', margin: '2px 4px', fontSize: '11px'},
  onChange: function () { updatePreview(); clearResultsForNewSelection(); }
});

var socCustomPanel = ui.Panel({
  widgets: [
    ui.Label('Asset ID', BODY_STYLE), socAssetBox,
    ui.Label('Band', BODY_STYLE), socBandBox,
    ui.Label('What the values mean', BODY_STYLE), socQuantitySelect,
    ui.Label('Multiply raw values by', BODY_STYLE), socScaleFactorBox,
    ui.Label('Leave at 1 unless your layer is stored scaled - a x10 integer ' +
             'store is common.', HINT_STYLE),
    ui.Label('Your layer is assumed to be the depth selected in Options.', HINT_STYLE)
  ],
  style: {shown: false}
});

/**
 * Rebuild the soil carbon dropdown for the selected depth.
 * @param {string} depth  a DEPTH_OPTIONS value
 */
function refreshSocOptions(depth) {
  var matching = socDatasetsForDepth(depth);
  var items = matching.map(function (d) {
    return {label: d.label, value: d.key};
  });
  items.push({label: 'Custom - my own GEE asset', value: CUSTOM_KEY});

  socSelect.items().reset(items);
  socSelect.setValue(matching.length ? matching[0].key : CUSTOM_KEY);

  socDepthNoteLabel.setValue(matching.length
    ? matching.length + ' global layer(s) available at ' + depth + ' cm.'
    : 'No global layer available at this depth - supply your own asset below.');
}

/**
 * @param {string} key
 * @return {string} the hint shown under the soil carbon dropdown
 */
function describeSocChoice(key) {
  if (key === CUSTOM_KEY) {
    return 'Your own asset. You must say what the values mean before it will compute.';
  }
  var cfg = getDatasetByKey(SOC_DATASETS, key);
  if (!cfg) { return ''; }
  return cfg.native_resolution_m + ' m, ' + cfg.depth_cm + ' cm, ' +
         QUANTITY[cfg.quantity].unit;
}

// =============================================================================
// UI - FOREST SECTION
// =============================================================================

var forestSelect = ui.Select({
  items: FOREST_DATASETS.map(function (d) { return {label: d.label, value: d.key}; })
                        .concat([{label: 'Custom - my own GEE asset', value: CUSTOM_KEY}]),
  value: FOREST_DATASETS[0].key,
  style: {stretch: 'horizontal', margin: '2px 4px'},
  onChange: function (key) {
    forestCustomPanel.style().set({shown: key === CUSTOM_KEY});
    updatePreview();
    clearResultsForNewSelection();
  }
});

var forestAssetBox = ui.Textbox({
  placeholder: 'projects/your-project/assets/national_forest_map',
  style: {stretch: 'horizontal', margin: '2px 4px', fontSize: '11px'},
  onChange: function () { updatePreview(); clearResultsForNewSelection(); }
});

var forestBandBox = ui.Textbox({
  placeholder: 'band name (blank = first band)',
  style: {stretch: 'horizontal', margin: '2px 4px', fontSize: '11px'},
  onChange: function () { updatePreview(); clearResultsForNewSelection(); }
});

var forestTypeSelect = ui.Select({
  items: [
    {label: 'Binary mask (1 = forest)', value: 'binary'},
    {label: 'Fractional cover (0-1)', value: 'fraction'}
  ],
  value: 'binary',
  style: {stretch: 'horizontal', margin: '2px 4px'},
  onChange: function () { updatePreview(); clearResultsForNewSelection(); }
});

var forestCustomPanel = ui.Panel({
  widgets: [
    ui.Label('Asset ID', BODY_STYLE), forestAssetBox,
    ui.Label('Band', BODY_STYLE), forestBandBox,
    ui.Label('What the values mean', BODY_STYLE), forestTypeSelect,
    ui.Label('Set the analysis scale to your layer\'s resolution in Options.', HINT_STYLE)
  ],
  style: {shown: false}
});

// =============================================================================
// UI - OPTIONS
// =============================================================================

var depthSelect = ui.Select({
  items: DEPTH_OPTIONS,
  value: '0-30',
  style: {stretch: 'horizontal', margin: '2px 4px'},
  onChange: function (depth) {
    refreshSocOptions(depth);
    updatePreview();
    clearResultsForNewSelection();
  }
});

var socDepthNoteLabel = ui.Label('', HINT_STYLE);

var scaleSelect = ui.Select({
  items: [{label: 'Native to soil layer', value: NATIVE_SCALE_KEY}]
      .concat(SCALE_OPTIONS.map(function (s) { return {label: s + ' m', value: s}; })),
  value: String(DEFAULT_SCALE),
  style: {stretch: 'horizontal', margin: '2px 4px'},
  // Scale changes no tile, only the statistics -- clear those, keep the map.
  onChange: function () { clearResultsForNewSelection(); }
});

var driveExportCheckbox = ui.Checkbox({
  label: 'Also queue a Drive export',
  value: false,
  style: {fontSize: '11px', margin: '4px'}
});

var optionsWidgets = [
  ui.Label('Soil depth', BODY_STYLE), depthSelect, socDepthNoteLabel,
  ui.Label('Only layers matching this depth are offered. Depths cannot be ' +
           'mixed - a 0-30 cm figure is not comparable with a deeper one.', HINT_STYLE),
  ui.Label('FRA does not mandate a depth: countries choose one and apply it ' +
           'consistently across the time series. Report whichever depth you ' +
           'used in the "Soil depth (cm) used for soil carbon" field. The ' +
           'global average countries report is 41 cm; the global layers here ' +
           'are 0-30 cm.', HINT_STYLE),
  ui.Label('Analysis scale', BODY_STYLE), scaleSelect,
  ui.Label('"Native to soil layer" runs on the carbon grid itself (GSOCmap ' +
           '~928 m, SoilGrids 250 m), so the values being averaged are never ' +
           'resampled - the original 2024 gap-filling ran this way. Coarser ' +
           'is faster; finer than the soil grid adds nothing.', HINT_STYLE)
];
if (!IS_PUBLISHED_APP) {
  optionsWidgets.push(driveExportCheckbox);
  optionsWidgets.push(ui.Label('Code Editor only - does nothing in a published app.', HINT_STYLE));
}

// =============================================================================
// UI - TOP BAR
// =============================================================================

var countrySelect = ui.Select({
  items: [GLOBAL_OPTION].concat(gaulLut.country_names),
  value: GLOBAL_OPTION,
  style: {width: '220px', margin: '4px 8px'},
  onChange: function (name) {
    if (!name) { return; }  // items().reset() can fire a null change
    if (name !== GLOBAL_OPTION) {
      map.centerObject(getRegions(name), 5);
    }
    updatePreview();
    clearResultsForNewSelection();
  }
});

// Filter the country list by FRA soil carbon status. 'reported' and 'desk'
// split the value-holders by who produced the figure -- the country itself,
// or FAO in a desk study (the gap-filled reports the tool exists to serve).
// Rebuilding the Select's items is the same pattern refreshSocOptions uses;
// values stay plain GAUL names so every downstream lookup is unchanged.
// 'gap' sits directly under 'all': the gap-filling audience is the main
// alternative to no filter, the provenance splits are the refinements.
var FRA_FILTER_MODES = [
  {label: 'All countries', value: 'all'},
  {label: 'No figure - a gap to fill', value: 'gap'},
  {label: 'Any FRA soil carbon figure', value: 'any'},
  {label: 'Country-reported figure', value: 'reported'},
  {label: 'FAO estimate (desk study)', value: 'desk'}
];

var fraFilterSelect = ui.Select({
  items: FRA_FILTER_MODES,
  value: 'all',
  onChange: function (mode) { rebuildCountryItems(mode); },
  style: {width: '190px', margin: '4px 8px 4px 0'}
});

function countryPassesFilter(name, mode) {
  if (mode === 'all') { return true; }
  var iso3 = nameToIso3[name];
  var hasFigure = iso3 ? fraSoc.hasValue(iso3) : false;
  if (mode === 'gap') {
    // The gap-filling audience: files FRA reports (has a forest-area row) but
    // no soil carbon value in any year. Territories outside FRA entirely are
    // not gaps -- there is no report to fill.
    return !hasFigure && !!fraStats.FRA_FOREST_AREA[name];
  }
  if (!hasFigure) { return false; }
  if (mode === 'any') { return true; }
  return fraSoc.isDeskStudy(iso3) === (mode === 'desk');
}

function rebuildCountryItems(mode) {
  var names = gaulLut.country_names.filter(function (n) {
    return countryPassesFilter(n, mode);
  });
  var current = countrySelect.getValue();
  countrySelect.items().reset([GLOBAL_OPTION].concat(names));
  var keep = (current === GLOBAL_OPTION) || (names.indexOf(current) !== -1);
  if (keep) {
    countrySelect.setValue(current, false);
  } else {
    // Fire the change: display, preview and results-clear all follow the one
    // onChange path, avoiding the Select's set-after-reset display race.
    countrySelect.setValue(GLOBAL_OPTION, true);
  }
}

// Staleness marker in the pff_4 style: one constant label, an appended '*'
// while the on-screen results (if any) no longer describe the selection.
// markRunStale is driven from clearResultsForNewSelection, the single choke
// point every layer- and option-widget already calls.
var RUN_LABEL = '▶ Run analysis';
var runStale = false;

var runButton = ui.Button({
  label: RUN_LABEL,
  onClick: function () { runAnalysis(); },
  style: {margin: '4px 8px', backgroundColor: '#4CAF50', fontSize: '12px'}
});

function markRunStale() {
  if (runStale) { return; }
  runStale = true;
  runButton.setLabel(RUN_LABEL + ' *');
}

function clearRunStale() {
  runStale = false;
  runButton.setLabel(RUN_LABEL);
}

var topBar = ui.Panel({
  widgets: [
    ui.Label('Forest Soil Carbon', {fontWeight: 'bold', fontSize: '18px', margin: '4px 8px'}),
    ui.Label('Country', {fontSize: '11px', margin: '8px 0 0 8px'}),
    countrySelect,
    ui.Label('Show', {fontSize: '11px', margin: '8px 0 0 0'}),
    fraFilterSelect,
    runButton,
    ui.Panel({style: {stretch: 'horizontal'}}),
    ui.Label('v' + APP_VERSION, {fontSize: '10px', color: '#888', margin: '8px'})
  ],
  layout: ui.Panel.Layout.flow('horizontal'),
  style: {
    stretch: 'horizontal',
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    padding: '4px',
    border: '1px solid #ccc'
  }
});

// =============================================================================
// UI - PANELS
// =============================================================================

var leftPanel = ui.Panel({
  widgets: [
    makeCollapsible('1. Forest layer', [forestSelect, forestCustomPanel], 'forestCollapsed'),
    makeCollapsible('2. Soil carbon layer', [socSelect, socNoteLabel, socCustomPanel], 'socCollapsed'),
    makeCollapsible('3. Options', optionsWidgets, 'optionsCollapsed')
  ],
  layout: ui.Panel.Layout.flow('vertical'),
  style: {width: '310px', backgroundColor: 'rgba(255, 255, 255, 0.95)', padding: '2px'}
});

var resultsPanel = ui.Panel({
  widgets: [ui.Label('Choose your layers, then Run analysis.', HINT_STYLE)],
  layout: ui.Panel.Layout.flow('vertical')
});

var inspectorPanel = ui.Panel({
  widgets: [ui.Label('Click the map to read pixel values.', HINT_STYLE)],
  layout: ui.Panel.Layout.flow('vertical')
});

var rightPanel = ui.Panel({
  widgets: [
    ui.Label('Results', HEADING_STYLE), resultsPanel,
    ui.Label('Pixel values', HEADING_STYLE), inspectorPanel
  ],
  layout: ui.Panel.Layout.flow('vertical'),
  style: {width: '310px', backgroundColor: 'rgba(255, 255, 255, 0.95)', padding: '2px'}
});

var map = ui.Map();
map.setCenter(0, 20, 2);
map.setControlVisibility({all: true});
map.style().set('cursor', 'crosshair');
map.onClick(function (coords) { inspectPixel(coords); });

var mainContainer = ui.Panel({
  widgets: [leftPanel, map, rightPanel],
  layout: ui.Panel.Layout.flow('horizontal'),
  style: {stretch: 'both'}
});

ui.root.widgets().reset([
  ui.Panel({
    widgets: [topBar, mainContainer],
    layout: ui.Panel.Layout.flow('vertical'),
    style: {stretch: 'both'}
  })
]);

refreshSocOptions(depthSelect.getValue());
socNoteLabel.setValue(describeSocChoice(socSelect.getValue()));
updatePreview();
uiReady = true;

// =============================================================================
// RUN
// =============================================================================

/**
 * Read the soil carbon dropdown, including the custom-asset case.
 * @return {Object|null} a SOC_DATASETS-shaped config, or null if incomplete
 */
function resolveSocConfig() {
  var key = socSelect.getValue();
  if (key !== CUSTOM_KEY) { return getDatasetByKey(SOC_DATASETS, key); }

  var asset = socAssetBox.getValue();
  if (!asset) { return null; }
  return {
    key: CUSTOM_KEY,
    label: 'My own soil carbon layer',
    asset: asset,
    band: socBandBox.getValue() || null,
    quantity: socQuantitySelect.getValue(),
    scale_factor: Number(socScaleFactorBox.getValue()) || 1,
    depth_cm: depthSelect.getValue(),
    native_resolution_m: null,
    citation: 'User-supplied asset: ' + asset
  };
}

/**
 * Read the forest dropdown, including the custom-asset case.
 * @return {Object|null} a FOREST_DATASETS-shaped config, or null if incomplete
 */
function resolveForestConfig() {
  var key = forestSelect.getValue();
  if (key !== CUSTOM_KEY) { return getDatasetByKey(FOREST_DATASETS, key); }

  var asset = forestAssetBox.getValue();
  if (!asset) { return null; }
  return {
    key: CUSTOM_KEY,
    label: 'My own forest layer',
    asset: asset,
    type: forestTypeSelect.getValue(),
    band: forestBandBox.getValue() || null,
    threshold: 0,
    year: null,
    citation: 'User-supplied asset: ' + asset
  };
}

function showMessage(text, style) {
  resultsPanel.add(ui.Label(text, style || BODY_STYLE));
}

// Native scale per asset, read once (a blocking getInfo) and cached for the
// session, so previews stay instant after the first native-scale lookup.
var nativeScaleCache = {};

function nativeScaleOf(assetId, band) {
  if (!(assetId in nativeScaleCache)) {
    var s = null;
    try {
      var img = ee.Image(assetId);
      img = band ? img.select([band]) : img.select([0]);
      s = img.projection().nominalScale().getInfo();
    } catch (e) {
      s = null;  // bad custom asset ID -- caller falls back
    }
    // The WGS84 default projection reports ~111 km: the asset carries no real
    // grid of its own (composites do this), so 'native' is meaningless.
    if (s !== null && s > 10000) { s = null; }
    nativeScaleCache[assetId] = s;
  }
  return nativeScaleCache[assetId];
}

/**
 * The analysis scale in metres for the current dropdown choice. 'native' is
 * the soil carbon layer's own grid -- carbon is the layer that must not be
 * resampled; forest fractions replicate to any grid without error.
 * @param {Object} socCfg
 * @return {number}
 */
function resolveAnalysisScale(socCfg) {
  var choice = scaleSelect.getValue();
  if (choice !== NATIVE_SCALE_KEY) { return Number(choice); }
  return nativeScaleOf(socCfg.asset, socCfg.band) || DEFAULT_SCALE;
}

/**
 * Resolve the current widget selections into configs, regions and images.
 * Pure read: no drawing, no server computation. Null when a custom config is
 * incomplete.
 * @return {Object|null}
 */
function buildRunContext() {
  var socCfg = resolveSocConfig();
  var forestCfg = resolveForestConfig();
  if (!socCfg || !forestCfg) { return null; }

  var countryName = countrySelect.getValue();
  if (!countryName) { return null; }  // transient during list rebuilds
  var scale = resolveAnalysisScale(socCfg);
  var isGlobal = (countryName === GLOBAL_OPTION);
  var regions = getRegions(countryName);

  var socImage = buildSocImage(socCfg);
  var forestArea = buildForestArea(forestCfg);
  var forestFraction = buildForestFraction(forestCfg);

  // Clip what is drawn to the selected country. The statistics are restricted
  // by reduceRegions over the same polygons, so clipping changes no number --
  // but it stops the map showing a global layer while the panel reports one
  // country, and it makes a click outside the border read "no data".
  function clipToCountry(img) {
    return isGlobal ? img : img.clip(regions);
  }

  return {
    socCfg: socCfg, forestCfg: forestCfg,
    countryName: countryName, scale: scale, isGlobal: isGlobal, regions: regions,
    socImage: socImage, forestArea: forestArea,
    socDisplay: clipToCountry(socImage),
    forestFractionDisplay: clipToCountry(forestFraction),
    forestAreaDisplay: clipToCountry(forestArea)
  };
}

/**
 * Draw a context's layers, replacing whatever is on the map.
 * @param {Object} ctx  from buildRunContext
 */
function drawLayers(ctx) {
  map.layers().reset();
  markerLayer = null;

  map.addLayer(ctx.socDisplay,
               ctx.socCfg.quantity === 'stock' ? SOC_STOCK_VIS : SOC_CONC_VIS,
               'Soil carbon (' + QUANTITY[ctx.socCfg.quantity].unit + ')', true, 0.8);
  map.addLayer(ctx.forestFractionDisplay.selfMask(), FOREST_VIS,
               'Forest: ' + ctx.forestCfg.label, true, 0.7);

  // The per-pixel product is only tonnes of carbon when the input is a stock.
  // For a concentration it is g/kg*ha, which is not a quantity -- do not draw
  // it and do not name it.
  if (QUANTITY[ctx.socCfg.quantity].summable) {
    map.addLayer(ctx.socDisplay.multiply(ctx.forestAreaDisplay).selfMask(),
                 SOC_IN_FOREST_VIS, 'Soil carbon in forest (t C per pixel)', false, 1);
  }

  // Outline the border so the clip is visibly a boundary, not a data gap.
  if (!ctx.isGlobal) {
    map.addLayer(
      ee.Image().byte().paint({featureCollection: ctx.regions, color: 1, width: 2}),
      {palette: ['#222222']}, 'Country boundary', true);
  }
}

/**
 * Redraw map and inspector for the current selection without computing
 * statistics. Tiles render lazily, so this costs no server computation.
 * Called from every layer-affecting widget: the map always shows what is
 * selected. Results are cleared separately -- figures for an abandoned
 * selection are worse than no figures.
 */
function updatePreview() {
  currentCtx = buildRunContext();
  inspectorPanel.clear();
  inspectorPanel.add(ui.Label('Click the map to read pixel values.', HINT_STYLE));
  if (!currentCtx) {
    map.layers().reset();
    markerLayer = null;
    return;
  }
  drawLayers(currentCtx);
}

function clearResultsForNewSelection() {
  if (!uiReady) { return; }
  resultsPanel.clear();
  // Red: this replaces figures the user may have been reading, and the map
  // now shows a selection those figures never described.
  resultsPanel.add(ui.Label('Selection changed - press Run analysis.', WARN_STYLE));
  markRunStale();
}

function runAnalysis() {
  resultsPanel.clear();

  var ctx = buildRunContext();
  if (!ctx) {
    showMessage('Enter the custom asset ID first.', WARN_STYLE);
    return;
  }
  currentCtx = ctx;
  drawLayers(ctx);
  inspectorPanel.clear();
  inspectorPanel.add(ui.Label('Click the map to read pixel values.', HINT_STYLE));

  var socCfg = ctx.socCfg;
  var forestCfg = ctx.forestCfg;
  var countryName = ctx.countryName;
  var scale = ctx.scale;
  var quantity = QUANTITY[socCfg.quantity];
  var socImage = ctx.socImage;
  var forestArea = ctx.forestArea;
  var regions = ctx.regions;

  showMessage(countryName, KICKER_STYLE);

  if (socCfg.quantity === 'unknown') {
    showMessage('Cannot compute.', HEADING_STYLE);
    showMessage('You have not told the app what the values in this layer mean. A stock ' +
                '(tonnes of carbon per hectare) and a concentration (grams of carbon ' +
                'per kilogram of soil) are different physical quantities, and the app ' +
                'cannot tell them apart from the pixel values.', WARN_STYLE);
    showMessage('The layer is on the map so you can inspect it. Over forest, a 0-30 cm ' +
                'stock usually reads about 30-150 t C/ha and a concentration about ' +
                '5-60 g/kg - but check the asset description rather than guessing.', HINT_STYLE);
    showMessage('Set "What the values mean" under Soil carbon layer, then Run again.');
    return;
  }

  // Only now is the selection actually being computed -- the unknown-quantity
  // return above leaves the '*' in place because nothing ran.
  clearRunStale();
  showMessage('Computing...', HINT_STYLE);

  // Statistics run on the UNCLIPPED images -- reduceRegions already restricts
  // to `regions`, so clipping first would just add work.
  var stats = computeCountryStats(socImage, forestArea, regions, scale, socCfg);

  computeTotals(stats, socCfg).evaluate(function (result, error) {
    resultsPanel.clear();
    showMessage(countryName, KICKER_STYLE);

    if (error) { showMessage('Failed: ' + error, WARN_STYLE); return; }
    if (!result || result.mean === null) {
      showMessage('No data returned. Try a coarser analysis scale.', WARN_STYLE);
      return;
    }

    var depthLabel = socCfg.depth_cm.replace('-', '–') + ' cm';
    // Both blocks share the same row labels (Soil carbon / Forest area), so
    // the estimate and the FRA report read as one line-by-line comparison.
    var estHead = 'Estimated from ' + (socCfg.short_label || socCfg.label) + ' · ' +
                  (forestCfg.short_label || forestCfg.label);

    // Below ~1 kha the bold mean would describe next to nothing -- say so on
    // the value itself, and print the area in hectares rather than a rounded
    // "0.0 kha".
    var tinyForest = result.forest_area_ha < 1000;
    var areaLine = tinyForest
        ? 'Forest area: ' + formatNumber(result.forest_area_ha, 0) + ' ha'
        : 'Forest area: ' + formatNumber(result.forest_area_ha / 1000, 1) + ' kha';

    if (quantity.summable) {
      showMessage(estHead, BLOCKHEAD_STYLE);
      showMessage('Soil carbon: ' + formatNumber(result.mean, 1) + ' t C/ha (mean, ' +
                  depthLabel + (tinyForest
                      ? ', over just ' + formatNumber(result.forest_area_ha, 0) +
                        ' ha of forest'
                      : '') + ')', EST_VALUE_STYLE);
      showMessage(areaLine);
      addReportedBlock(socCfg, countryName);
    } else {
      showMessage(estHead, BLOCKHEAD_STYLE);
      showMessage('Soil carbon concentration: ' + formatNumber(result.mean, 1) +
                  ' g/kg (mean, ' + depthLabel + ')', EST_VALUE_STYLE);
      showMessage(areaLine);
      // No reported block here: FRA values are stocks, and echoing them beside
      // a concentration invites exactly the comparison this warning forbids.
      showMessage('NOT the FRA figure. This layer is a concentration - how carbon-rich ' +
                  'the soil is. FRA asks for a stock - how much carbon is there, in ' +
                  'tonnes per hectare. A g/kg value cannot be entered in place of a ' +
                  't C/ha value.', WARN_STYLE);
    }

    // Both expanders start closed on every run.
    appState.ui.qualityCollapsed = true;
    appState.ui.detailsCollapsed = true;

    var q = buildQualityWidgets(socCfg, countryName, result.coverage_pc);
    if (q.widgets.length) {
      resultsPanel.add(makeCollapsible('Soil data quality', q.widgets, 'qualityCollapsed',
                                       q.caution ? AMBER_BTN : null));
    }
    resultsPanel.add(makeCollapsible(
        'Details',
        buildDetailsWidgets(result, socCfg, forestCfg, countryName, scale),
        'detailsCollapsed'));

    addDownloadLink(stats, socCfg, forestCfg, countryName, scale);
  });

  if (!IS_PUBLISHED_APP && driveExportCheckbox.getValue()) {
    Export.table.toDrive({
      collection: stats,
      folder: 'fra_soc_gap_filling',
      description: 'soc_in_forest_' + forestCfg.key + '_' + socCfg.key,
      fileFormat: 'CSV'
    });
    showMessage('Drive export queued - see the Tasks tab.', HINT_STYLE);
  }
}

// =============================================================================
// PIXEL INSPECTOR
// The inputs are continuous (soil carbon per hectare, fractional forest cover),
// so the value at a point is worth reading directly -- it is how you tell a
// suspicious country mean from a genuine one, and how you check a national
// asset's units and scale factor before trusting a whole run.
// =============================================================================

function showInspectorMessage(text, style) {
  inspectorPanel.add(ui.Label(text, style || BODY_STYLE));
}

/**
 * Sample every layer of the current selection at a clicked point.
 * @param {Object} coords  {lon, lat} from ui.Map.onClick
 */
function inspectPixel(coords) {
  inspectorPanel.clear();

  if (!currentCtx) {
    showInspectorMessage('Choose layers first - a custom asset needs its ID entered.',
                         HINT_STYLE);
    return;
  }

  var point = ee.Geometry.Point([coords.lon, coords.lat]);

  if (markerLayer) { map.layers().remove(markerLayer); }
  markerLayer = ui.Map.Layer(point, {color: 'red'}, 'Inspected point');
  map.layers().add(markerLayer);

  showInspectorMessage(formatNumber(coords.lat, 4) + ', ' +
                       formatNumber(coords.lon, 4), HEADING_STYLE);
  showInspectorMessage('Reading...', HINT_STYLE);

  var quantity = QUANTITY[currentCtx.socCfg.quantity];

  // One band per reported value, so this costs a single server round trip.
  var stack = currentCtx.socDisplay.rename('soc_value')
    .addBands(currentCtx.forestFractionDisplay.rename('forest_fraction'))
    .addBands(currentCtx.forestAreaDisplay.rename('forest_area_ha'));

  stack.reduceRegion({
    reducer: ee.Reducer.first(),
    geometry: point,
    scale: currentCtx.scale
  }).evaluate(function (values, error) {
    inspectorPanel.clear();
    showInspectorMessage(formatNumber(coords.lat, 4) + ', ' +
                         formatNumber(coords.lon, 4), HEADING_STYLE);

    if (error) {
      showInspectorMessage('Could not read this point: ' + error, WARN_STYLE);
      return;
    }
    if (!values) {
      showInspectorMessage('No data at this point.', HINT_STYLE);
      return;
    }

    // null means masked -- no data here -- which is different from zero and is
    // worth saying, because masked soil pixels are what drag the coverage down.
    var soc = values.soc_value;
    var fraction = values.forest_fraction;
    var areaHa = values.forest_area_ha;

    var isBlank = function (v) { return v === null || v === undefined; };

    // Everything masked with a country selected means the click landed outside
    // the clip, which is a different thing from a genuine data gap inside it.
    if (!currentCtx.isGlobal && isBlank(soc) && isBlank(fraction) && isBlank(areaHa)) {
      showInspectorMessage('Outside ' + currentCtx.countryName + '. The layers are clipped ' +
                           'to the selected country - click inside the border, or switch ' +
                           'to ' + GLOBAL_OPTION + '.', HINT_STYLE);
      return;
    }

    showInspectorMessage('Soil carbon: ' + (soc === null || soc === undefined
      ? 'no data'
      : formatNumber(soc, 1) + ' ' + quantity.unit));

    showInspectorMessage('Forest cover: ' + (fraction === null || fraction === undefined
      ? 'no data'
      : formatNumber(fraction * 100, 1) + '% of pixel'));

    showInspectorMessage('Forest area: ' + (areaHa === null || areaHa === undefined
      ? 'no data'
      : formatNumber(areaHa, 1) + ' ha in pixel'));

    if (quantity.summable && soc !== null && soc !== undefined &&
        areaHa !== null && areaHa !== undefined) {
      showInspectorMessage('Carbon in forest here: ' +
                           formatNumber(soc * areaHa, 1) + ' t C in pixel', HINT_STYLE);
    }

    if ((soc === null || soc === undefined) && areaHa) {
      showInspectorMessage('Forest with no soil carbon data - this pixel is excluded ' +
                           'from the country mean and counts against the coverage %.',
                           WARN_STYLE);
    }

    showInspectorMessage('Sampled at ' + formatNumber(currentCtx.scale, 1) + ' m. Values ' +
                         'are the analysis scale, not the layer\'s native resolution.',
                         HINT_STYLE);
  });
}

/**
 * Upper bound in cm of the app's depth selection, for comparability checks
 * against the depth a country reported to FRA.
 * @param {string} depthCm  a DEPTH_OPTIONS value
 * @return {number|null} null for 'other' -- no comparison possible
 */
function depthUpperCm(depthCm) {
  if (depthCm === '0-30') { return 30; }
  if (depthCm === '0-100') { return 100; }
  return null;
}

/**
 * The "Reported in FRA" block: soil carbon first, aligned with the estimate
 * above it, then forest area. The rows degrade independently -- a country can
 * have an area row and no soil figure, which is exactly the gap-filling
 * audience. Stocks only: FRA has no concentration to echo. Desk-study values
 * are labelled as FAO estimates so the app never validates its own method
 * against itself.
 * @param {Object} socCfg
 * @param {string} countryName
 */
function addReportedBlock(socCfg, countryName) {
  if (countryName === GLOBAL_OPTION) { return; }
  if (!QUANTITY[socCfg.quantity].summable) { return; }

  var iso3 = nameToIso3[countryName] || null;
  var inFra = iso3 ? fraSoc.hasReport(iso3) : false;
  var areaRow = fraStats.FRA_FOREST_AREA[countryName];
  var areaKha = areaRow ? areaRow[FRA_REPORTED.year] : null;

  if (!inFra && (areaKha === null || areaKha === undefined)) {
    showMessage('No FRA report for this territory.', HINT_STYLE);
    return;
  }

  showMessage('Reported in ' + FRA_REPORTED.cycle + ' (' + FRA_REPORTED.year + ' value)',
              BLOCKHEAD_STYLE);

  // Some series stop before the comparison year (Ukraine ends 2010): fall
  // back to the most recent value rather than telling a filtered-in country
  // it has no figure, and say on the row which year it is.
  var soc = iso3 ? fraSoc.getSoc(iso3, FRA_REPORTED.year) : null;
  var socYear = FRA_REPORTED.year;
  if (!soc && iso3) {
    soc = fraSoc.getLatestSoc(iso3);
    if (soc) { socYear = soc.year; }
  }
  if (soc) {
    var suffix;
    if (soc.deskStudy) {
      suffix = 'FAO estimate, not country-reported';
    } else if (soc.depthCm) {
      suffix = 'reported at ' + Math.round(soc.depthCm) + ' cm';
      var upper = depthUpperCm(socCfg.depth_cm);
      if (upper !== null && Math.round(soc.depthCm) !== upper) {
        suffix += ' - not comparable with a ' + socCfg.depth_cm + ' cm estimate';
      }
    } else {
      suffix = 'depth not stated';
    }
    if (String(socYear) !== String(FRA_REPORTED.year)) {
      suffix = socYear + ', latest available - ' + suffix;
    }
    showMessage('Soil carbon: ' + formatNumber(soc.value, 1) + ' t/ha (' + suffix + ')');
    // 2d's second reporting table. Usually one of the pair is entered and the
    // platform derives the other from table 1a forest area -- say which.
    var tot = fraSoc.getSocTotal(iso3, socYear);
    if (tot) {
      showMessage('Total soil carbon: ' + formatNumber(tot.value, 1) + ' Mt (' +
                  (tot.calculated ? 'platform-derived' : 'country-entered') + ')');
    }
  } else {
    showMessage('Soil carbon: no figure in the country report');
  }

  if (areaKha !== null && areaKha !== undefined) {
    showMessage('Forest area: ' + formatNumber(areaKha, 1) + ' kha');
  }
}

/**
 * Content for the "Soil data quality" expander: the dataset's own per-country
 * brief (config key `meta_brief`) plus this run's coverage. caution decides
 * the toggle's amber tint. Generic -- reads only config keys.
 * @param {Object} socCfg
 * @param {string} countryName
 * @param {number|null} coveragePc
 * @return {Object} {widgets: Array, caution: boolean}
 */
function buildQualityWidgets(socCfg, countryName, coveragePc) {
  var widgets = [];
  var brief = (socCfg.meta_brief && countryName !== GLOBAL_OPTION)
      ? socCfg.meta_brief(nameToIso3[countryName] || countryName) : null;
  if (brief) { widgets.push(ui.Label(brief.text, HINT_STYLE)); }
  var hasCoverage = (coveragePc !== null && coveragePc !== undefined);
  if (hasCoverage) {
    widgets.push(ui.Label('Soil data covers ' + formatNumber(coveragePc, 1) +
                          '% of the forest in this run.',
                          coveragePc < LOW_COVERAGE_WARN_PC ? WARN_STYLE : HINT_STYLE));
  }
  var caution = (brief !== null && brief.caution) ||
                (hasCoverage && coveragePc < LOW_COVERAGE_WARN_PC);
  return {widgets: widgets, caution: caution};
}

/**
 * Everything that used to crowd the results panel, behind one expander.
 * @return {Array} widgets for makeCollapsible
 */
function buildDetailsWidgets(result, socCfg, forestCfg, countryName, scale) {
  var w = [];
  if (QUANTITY[socCfg.quantity].summable) {
    w.push(ui.Label('Total soil carbon in forest: ' +
                    formatNumber(result.soc_in_forest_total / 1e6, 1) + ' Mt C.', BODY_STYLE));
    w.push(ui.Label('FRA table 2d takes both the mean (t C/ha, depth in "Soil depth (cm) ' +
                    'used for soil carbon") and a total (million tonnes); the platform ' +
                    'derives whichever is left blank from table 1a forest area.', HINT_STYLE));
  } else {
    w.push(ui.Label('No total is shown: adding up a concentration over an area does not ' +
                    'give a carbon stock. Converting one to the other needs bulk density ' +
                    'and coarse-fragment maps, which this app does not do.', HINT_STYLE));
  }
  w.push(ui.Label('Forest: ' + forestCfg.label, HINT_STYLE));
  w.push(ui.Label('Soil carbon: ' + socCfg.label, HINT_STYLE));
  w.push(ui.Label(socCfg.depth_cm + ' cm ' + socCfg.quantity + ', analysed at ' +
                  formatNumber(scale, 1) + ' m', HINT_STYLE));
  if (socCfg.meta_format && countryName !== GLOBAL_OPTION) {
    var line = socCfg.meta_format(nameToIso3[countryName] || countryName);
    if (line) {
      w.push(ui.Label('Map provenance - ' + line, HINT_STYLE));
    } else if (socCfg.meta_missing) {
      w.push(ui.Label(socCfg.meta_missing, HINT_STYLE));
    }
  }
  w.push(ui.Label(socCfg.citation, HINT_STYLE));
  w.push(ui.Label(forestCfg.citation, HINT_STYLE));
  w.push(ui.Label(fraSoc.CITATION, HINT_STYLE));
  return w;
}

/**
 * Add an in-app CSV download link. Works in a published app, unlike
 * Export.table.toDrive. The mean column name carries its unit, and the total
 * column is omitted entirely when it would not be a meaningful quantity.
 * @param {ee.FeatureCollection} stats
 * @param {Object} socCfg
 * @param {Object} forestCfg
 * @param {string} countryName
 * @param {number} scale
 */
function addDownloadLink(stats, socCfg, forestCfg, countryName, scale) {
  var selectors = ['iso3', 'country', 'forest_area_ha', 'forest_area_with_soc_ha',
                   'soc_data_coverage_pc'];
  if (QUANTITY[socCfg.quantity].summable) {
    selectors.push('soc_in_forest_total');
  }
  selectors.push(meanColumnName(socCfg));
  // Audit-record columns: constants describing the run, on every row, so the
  // CSV alone can justify a figure later.
  selectors = selectors.concat(['soc_dataset', 'forest_dataset', 'depth_cm',
                                'analysis_scale_m', 'boundaries', 'app_version',
                                'run_date']);
  var runDate = new Date().toISOString().slice(0, 10);
  stats = stats.map(function (f) {
    return f.set({
      soc_dataset: socCfg.label,
      forest_dataset: forestCfg.label,
      depth_cm: socCfg.depth_cm,
      analysis_scale_m: scale,
      boundaries: 'GAUL 2024 L0',
      app_version: APP_VERSION,
      run_date: runDate
    });
  });

  var slug = (countryName === GLOBAL_OPTION
    ? 'global'
    : countryName.replace(/[^A-Za-z0-9]+/g, '_'));

  var url = stats.getDownloadURL({
    format: 'csv',
    selectors: selectors,
    filename: 'soc_in_forest_' + slug + '_' + forestCfg.key + '_' + socCfg.key +
              '_' + socCfg.depth_cm + 'cm_' + scale + 'm'
  });

  resultsPanel.add(ui.Label({
    value: '↓ Download record (CSV)',
    style: LINK_STYLE,
    targetUrl: url
  }));
}
